import { useState } from "react";
import { useRouter } from "@tanstack/react-router";
import type { MasterWhiteLabelDetail } from "../../lib/server/master-white-label.types.ts";
import { createMasterDomain,setMasterDomainStatus,updateMasterDomain } from "../../lib/server/master-white-label.functions.ts";

export function MasterWhiteLabelDomainManager({detail}:Readonly<{detail:MasterWhiteLabelDetail}>):React.JSX.Element{
  const router=useRouter();const [busy,setBusy]=useState(false);const [message,setMessage]=useState("");
  async function create(event:React.SyntheticEvent<HTMLFormElement>):Promise<void>{event.preventDefault();const form=new FormData(event.currentTarget);setBusy(true);setMessage("");try{const type=String(form.get("type")??"tenant_panel") as "tenant_panel"|"tenant_site"|"store_admin"|"store_catalog";await createMasterDomain({data:{tenantId:detail.tenant.id,hostname:String(form.get("hostname")??""),type,storeId:String(form.get("storeId")??"").trim()||null}});setMessage("Domínio criado como pending. Verificação real é necessária antes de ativar.");event.currentTarget.reset();await router.invalidate();}catch(error){setMessage(error instanceof Error?error.message:"Falha ao criar domínio.");}finally{setBusy(false);}}
  async function edit(domain:MasterWhiteLabelDetail["domains"][number],form:HTMLFormElement):Promise<void>{const data=new FormData(form);setBusy(true);setMessage("");try{const type=String(data.get("type")??domain.type) as "tenant_panel"|"tenant_site"|"store_admin"|"store_catalog";await updateMasterDomain({data:{tenantId:detail.tenant.id,domainId:domain.id,hostname:String(data.get("hostname")??domain.hostname),type,storeId:String(data.get("storeId")??"").trim()||null}});setMessage("Domínio atualizado e retornado para pending até nova verificação.");await router.invalidate();}catch(error){setMessage(error instanceof Error?error.message:"Falha ao atualizar domínio.");}finally{setBusy(false);}}
  async function changeStatus(domainId:string,status:"pending"|"suspended"):Promise<void>{setBusy(true);setMessage("");try{await setMasterDomainStatus({data:{tenantId:detail.tenant.id,domainId,status}});await router.invalidate();}catch(error){setMessage(error instanceof Error?error.message:"Falha ao alterar domínio.");}finally{setBusy(false);}}
  return <section className="master-card master-panel"><h2>Domínios</h2><form className="k-form" onSubmit={(event)=>{void create(event);}}><div className="k-form__grid"><div className="k-field"><label htmlFor="domain-host">Hostname</label><input id="domain-host" name="hostname" required/></div><div className="k-field"><label htmlFor="domain-type">Tipo</label><select id="domain-type" name="type" defaultValue="tenant_panel"><option value="tenant_panel">tenant_panel</option><option value="tenant_site">tenant_site</option><option value="store_admin">store_admin</option><option value="store_catalog">store_catalog</option></select></div><div className="k-field"><label htmlFor="domain-store">Store ID (somente tipos store_*)</label><input id="domain-store" name="storeId"/></div></div><div className="k-actions"><button className="k-button" disabled={busy}>Adicionar domínio</button></div></form>{message?<div className="k-status">{message}</div>:null}{detail.domains.length?<div>{detail.domains.map((domain)=><form className="k-form" key={domain.id} onSubmit={(event)=>{event.preventDefault();void edit(domain,event.currentTarget);}}><div className="k-form__grid"><div className="k-field"><label>Hostname</label><input name="hostname" defaultValue={domain.hostname}/></div><div className="k-field"><label>Tipo</label><select name="type" defaultValue={domain.type}><option value="tenant_panel">tenant_panel</option><option value="tenant_site">tenant_site</option><option value="store_admin">store_admin</option><option value="store_catalog">store_catalog</option></select></div><div className="k-field"><label>Store ID</label><input name="storeId" defaultValue={domain.storeId??""}/></div></div><p className="k-muted">Status: {domain.status} · Verificado: {domain.verifiedAt?"Sim":"Não"}</p><div className="k-actions"><button className="k-button" disabled={busy}>Salvar domínio</button><button className="k-button" type="button" disabled={busy} onClick={()=>{void changeStatus(domain.id,domain.status==="suspended"?"pending":"suspended");}}>{domain.status==="suspended"?"Voltar a pending":"Suspender"}</button></div></form>)}</div>:<p className="k-muted">Nenhum domínio cadastrado.</p>}</section>;
}
