import { afterAll,beforeAll,describe,expect,test } from "bun:test";import { readFileSync } from "node:fs";import { join } from "node:path";import { setupDatabase } from "./harness.ts";import type { Harness } from "./harness.ts";import { createWhiteLabelDomain,updateWhiteLabelDomain } from "../../apps/web/src/lib/server/master-white-label.write.server.ts";import { seedIds,seedSql } from "./seed.ts";
let h:Harness;const ids=seedIds();const actor=ids.users.platformOwner;beforeAll(async()=>{h=await setupDatabase();await h.db.execScript(seedSql());await h.db.execScript(readFileSync(join(import.meta.dir,"..","..","supabase","migrations","0015_master_white_label_management.sql"),"utf8"));});afterAll(async()=>{await h.db.close();});
describe("master domain management",()=>{
test("domínio novo fica pending e não verificado",async()=>{const result=await createWhiteLabelDomain(h.db,actor,{tenantId:ids.tenantA,hostname:"painel-a.example.com",type:"tenant_panel",storeId:null});expect(result.status).toBe("pending");expect((await h.db.query("select status,verified_at from public.domains where id=$1::uuid",[result.id]))[0]).toMatchObject({status:"pending",verified_at:null});});
test("hostname duplicado falha mesmo pending",async()=>{await createWhiteLabelDomain(h.db,actor,{tenantId:ids.tenantA,hostname:"dup.example.com",type:"tenant_panel",storeId:null});await expect(createWhiteLabelDomain(h.db,actor,{tenantId:ids.tenantB,hostname:"dup.example.com",type:"tenant_panel",storeId:null})).rejects.toThrow("já está cadastrado");});
test("hostname reservado falha",async()=>{await expect(createWhiteLabelDomain(h.db,actor,{tenantId:ids.tenantA,hostname:"app.kataluu.com.br",type:"tenant_panel",storeId:null})).rejects.toThrow("reservado");});
test("store de outro tenant não pode ser associada",async()=>{await expect(createWhiteLabelDomain(h.db,actor,{tenantId:ids.tenantA,hostname:"cross.example.com",type:"store_admin",storeId:ids.storeB})).rejects.toThrow("Escopo");});
test("edição volta para pending e limpa verificação",async()=>{const created=await createWhiteLabelDomain(h.db,actor,{tenantId:ids.tenantA,hostname:"before.example.com",type:"tenant_panel",storeId:null});await h.db.query("update public.domains set status='active',verified_at=now() where id=$1::uuid",[created.id]);await updateWhiteLabelDomain(h.db,actor,{tenantId:ids.tenantA,domainId:created.id,hostname:"after.example.com",type:"tenant_panel",storeId:null});expect((await h.db.query("select hostname,status,verified_at from public.domains where id=$1::uuid",[created.id]))[0]).toMatchObject({hostname:"after.example.com",status:"pending",verified_at:null});});
});
