import { afterAll, beforeAll, describe, expect, test } from "bun:test";
import { setupDatabase } from "./harness.ts";
import type { Harness } from "./harness.ts";
import { changeWhiteLabelOwner, createWhiteLabel, setWhiteLabelStatus, updateWhiteLabel } from "../../apps/web/src/lib/server/master-white-label.write.server.ts";

let h: Harness;
const actor = "11111111-1111-4111-8111-111111111111";
const ownerA = "22222222-2222-4222-8222-222222222222";
const ownerB = "33333333-3333-4333-8333-333333333333";
const missingOwner = "44444444-4444-4444-8444-444444444444";
beforeAll(async () => { h = await setupDatabase(); await h.db.execScript("create table if not exists auth.users(id uuid primary key,email text);"); await h.db.query("insert into auth.users(id,email) values ($1,'a@example.com'),($2,'b@example.com')", [ownerA, ownerB]); });
afterAll(async () => { await h.db.close(); });

describe("master White Label management", () => {
  test("criação válida associa owner e audita", async () => { const result = await createWhiteLabel(h.db, actor, { name: "Acme", slug: "acme", ownerUserId: ownerA }); expect(result.created).toBe(true); const rows = await h.db.query(`select t.name,tm.role,b.tenant_id is not null branding,s.tenant_id is not null settings from public.tenants t join public.tenant_members tm on tm.tenant_id=t.id and tm.user_id=$1 left join public.tenant_branding b on b.tenant_id=t.id left join public.tenant_settings s on s.tenant_id=t.id where t.id=$2::uuid`, [ownerA, result.id]); expect(rows[0]).toMatchObject({ name: "Acme", role: "tenant_owner", branding: true, settings: true }); const audit = await h.db.query("select action from public.audit_logs where tenant_id=$1::uuid", [result.id]); expect(audit.some((row) => row["action"] === "master.white_label.created")).toBe(true); });
  test("retry idêntico é idempotente", async () => { const first = await createWhiteLabel(h.db, actor, { name: "Retry", slug: "retry", ownerUserId: ownerA }); const second = await createWhiteLabel(h.db, actor, { name: "Retry", slug: "retry", ownerUserId: ownerA }); expect(second.id).toBe(first.id); expect(second.created).toBe(false); expect((await h.db.query("select count(*)::int count from public.tenants where slug='retry'"))[0]?.["count"]).toBe(1); });
  test("falha de owner não deixa tenant parcial", async () => { expect(createWhiteLabel(h.db, actor, { name: "Rollback", slug: "rollback", ownerUserId: missingOwner })).rejects.toThrow("não existe"); expect(await h.db.query("select id from public.tenants where slug='rollback'")).toHaveLength(0); });
  test("troca owner mantém exatamente um tenant_owner", async () => { const created = await createWhiteLabel(h.db, actor, { name: "Owner", slug: "owner", ownerUserId: ownerA }); await changeWhiteLabelOwner(h.db, actor, created.id, ownerB); const rows = await h.db.query("select user_id::text,role from public.tenant_members where tenant_id=$1::uuid", [created.id]); expect(rows.filter((row) => row["role"] === "tenant_owner")).toHaveLength(1); expect(rows.find((row) => row["role"] === "tenant_owner")?.["user_id"]).toBe(ownerB); });
  test("owner inválido preserva owner atual", async () => { const created = await createWhiteLabel(h.db, actor, { name: "Safe", slug: "safe", ownerUserId: ownerA }); expect(changeWhiteLabelOwner(h.db, actor, created.id, missingOwner)).rejects.toThrow("não existe"); expect((await h.db.query("select user_id::text from public.tenant_members where tenant_id=$1::uuid and role='tenant_owner'", [created.id]))[0]?.["user_id"]).toBe(ownerA); });
  test("edição e suspensão/reativação persistem e auditam", async () => { const created = await createWhiteLabel(h.db, actor, { name: "Editar", slug: "editar", ownerUserId: ownerA }); await updateWhiteLabel(h.db, actor, { tenantId: created.id, name: "Editada", slug: "editada", logoUrl: null, primaryColor: "#112233", settings: { locale: "pt-BR" } }); expect((await setWhiteLabelStatus(h.db, actor, created.id, "suspended")).status).toBe("suspended"); expect((await setWhiteLabelStatus(h.db, actor, created.id, "active")).status).toBe("active"); expect((await h.db.query("select name,slug,status from public.tenants where id=$1::uuid", [created.id]))[0]).toMatchObject({ name: "Editada", slug: "editada", status: "active" }); const audits = await h.db.query("select action from public.audit_logs where tenant_id=$1::uuid", [created.id]); const actions = audits.map((row) => row["action"]); expect(actions).toContain("master.white_label.updated"); expect(actions).toContain("master.white_label.suspended"); expect(actions).toContain("master.white_label.reactivated"); });
});
