/* eslint-disable @typescript-eslint/no-unnecessary-condition,@typescript-eslint/no-misused-spread,@typescript-eslint/restrict-template-expressions,@typescript-eslint/no-unsafe-return */
import { createHash,randomBytes } from "node:crypto";
import { createCredentialVaultFromEnv } from "@white-label/payments/server";
import type { CatalogScope } from "@white-label/catalog";
import { createAdminSqlExecutor } from "./supabase-admin.server.ts";
const vault=()=>createCredentialVaultFromEnv();const sql=()=>createAdminSqlExecutor();
const env=(n:string)=>{const v=process.env[n]?.trim();if(!v)throw new Error(`Configuração obrigatória ausente: ${n}`);return v};
const base=()=>process.env["MELHOR_ENVIO_BASE_URL"]?.trim()||"https://melhorenvio.com.br";
const ua=()=>process.env["MELHOR_ENVIO_USER_AGENT"]?.trim()||"Kataluu (suporte@kataluu.com.br)";
const hash=(v:string)=>createHash("sha256").update(v).digest("hex");
async function token(scope:CatalogScope){const rows=await sql().query(`select access_token_ciphertext,refresh_token_ciphertext,access_token_expires_at from private.melhor_envio_accounts where tenant_id=$1::uuid and store_id=$2::uuid`,[scope.tenantId,scope.storeId]);const r=rows[0];if(!r)throw new Error("Melhor Envio não conectado.");if(new Date(String(r["access_token_expires_at"])).getTime()>Date.now()+300000)return vault().decrypt(String(r["access_token_ciphertext"]));const body=new URLSearchParams({grant_type:"refresh_token",client_id:env("MELHOR_ENVIO_CLIENT_ID"),client_secret:env("MELHOR_ENVIO_CLIENT_SECRET"),refresh_token:vault().decrypt(String(r["refresh_token_ciphertext"]))});const res=await fetch(`${base()}/oauth/token`,{method:"POST",headers:{"User-Agent":ua(),"Content-Type":"application/x-www-form-urlencoded",Accept:"application/json"},body});const j=await res.json() as Record<string,unknown>;if(!res.ok||typeof j["access_token"]!=="string"||typeof j["refresh_token"]!=="string")throw new Error("Não foi possível renovar a conexão com Melhor Envio.");await sql().query(`update private.melhor_envio_accounts set access_token_ciphertext=$3,refresh_token_ciphertext=$4,access_token_expires_at=now()+($5::int*interval '1 second'),updated_at=now() where tenant_id=$1::uuid and store_id=$2::uuid`,[scope.tenantId,scope.storeId,vault().encrypt(j["access_token"]),vault().encrypt(j["refresh_token"]),Number(j["expires_in"]??2592000)]);return j["access_token"];}
export async function melhorEnvioRequest(scope:CatalogScope,path:string,init:RequestInit={}){const access=await token(scope);const res=await fetch(`${base()}${path}`,{...init,headers:{Authorization:`Bearer ${access}`,"User-Agent":ua(),Accept:"application/json","Content-Type":"application/json",...(init.headers??{})}});if(!res.ok)throw new Error(`Melhor Envio recusou a operação (${res.status}).`);return res.status===204?null:res.json();}
export async function startMelhorEnvioOAuth(scope:CatalogScope,userId:string,host:string){const state=randomBytes(32).toString("base64url"),returnUrl=`https://${host.split(":")[0]}/admin/settings`;await sql().query(`insert into private.melhor_envio_oauth_states(state_hash,tenant_id,store_id,actor_user_id,return_url,expires_at) values($1,$2::uuid,$3::uuid,$4::uuid,$5,now()+interval '10 minutes')`,[hash(state),scope.tenantId,scope.storeId,userId,returnUrl]);const u=new URL(`${base()}/oauth/authorize`);u.searchParams.set("client_id",env("MELHOR_ENVIO_CLIENT_ID"));u.searchParams.set("redirect_uri",env("MELHOR_ENVIO_REDIRECT_URI"));u.searchParams.set("response_type","code");u.searchParams.set("state",state);u.searchParams.set("scope","shipping-calculate shipping-checkout shipping-generate shipping-print shipping-tracking ecommerce-shipping users-read");return u.toString();}
export async function finishMelhorEnvioOAuth(code:string,state:string,userId:string){const rows=await sql().query(`update private.melhor_envio_oauth_states set consumed_at=now() where state_hash=$1 and actor_user_id=$2::uuid and consumed_at is null and expires_at>now() returning tenant_id::text,store_id::text,return_url`,[hash(state),userId]);const r=rows[0];if(!r)throw new Error("Autorização Melhor Envio inválida ou expirada.");const body=new URLSearchParams({grant_type:"authorization_code",client_id:env("MELHOR_ENVIO_CLIENT_ID"),client_secret:env("MELHOR_ENVIO_CLIENT_SECRET"),redirect_uri:env("MELHOR_ENVIO_REDIRECT_URI"),code});const res=await fetch(`${base()}/oauth/token`,{method:"POST",headers:{"User-Agent":ua(),Accept:"application/json","Content-Type":"application/x-www-form-urlencoded"},body});const j=await res.json() as Record<string,unknown>;if(!res.ok||typeof j["access_token"]!=="string"||typeof j["refresh_token"]!=="string")throw new Error("Melhor Envio recusou a autorização.");await sql().query(`insert into private.melhor_envio_accounts(tenant_id,store_id,access_token_ciphertext,refresh_token_ciphertext,access_token_expires_at) values($1::uuid,$2::uuid,$3,$4,now()+($5::int*interval '1 second')) on conflict(store_id) do update set access_token_ciphertext=excluded.access_token_ciphertext,refresh_token_ciphertext=excluded.refresh_token_ciphertext,access_token_expires_at=excluded.access_token_expires_at,updated_at=now()`,[r["tenant_id"],r["store_id"],vault().encrypt(j["access_token"]),vault().encrypt(j["refresh_token"]),Number(j["expires_in"]??2592000)]);return String(r["return_url"]);}
