/* eslint-disable @typescript-eslint/no-unnecessary-condition */
import { createServerFn } from "@tanstack/react-start";import { getRequestHost } from "@tanstack/react-start/server";import { z } from "zod";import { createMerchantCatalogContext } from "./catalog-context.server.ts";import { finishMelhorEnvioOAuth, startMelhorEnvioOAuth } from "./melhor-envio.server.ts";
import { resolveSessionFromRequest } from "./session.server.ts";
import { buyOrderShipment } from "./order-shipping.server.ts";import { createAdminSqlExecutor } from "./supabase-admin.server.ts";
const profile=z.object({postalCode:z.string().transform(v=>v.replace(/\D/g,"")).refine(v=>v.length===8),shipperName:z.string().trim().min(2).max(160),shipperEmail:z.string().email(),shipperPhone:z.string().trim().min(8).max(30),document:z.string().nullable(),companyDocument:z.string().nullable(),stateRegister:z.string().nullable(),address:z.string().min(2),number:z.string().min(1),complement:z.string().nullable(),district:z.string().min(2),city:z.string().min(2),stateAbbr:z.string().length(2),enabled:z.boolean()});
export const getMelhorEnvioSettings=createServerFn({method:"GET"}).handler(async()=>{const c=await createMerchantCatalogContext(getRequestHost()),rows=await createAdminSqlExecutor().query(`select p.*,a.store_id is not null connected from public.store_shipping_profiles p full join private.melhor_envio_accounts a on a.tenant_id=p.tenant_id and a.store_id=p.store_id where coalesce(p.tenant_id,a.tenant_id)=$1::uuid and coalesce(p.store_id,a.store_id)=$2::uuid limit 1`,[c.scope.tenantId,c.scope.storeId]);const r=rows[0];return {connected:r?.["connected"]===true,postalCode:typeof r?.["postal_code"]==="string"?r["postal_code"]:null,shipperName:typeof r?.["shipper_name"]==="string"?r["shipper_name"]:null,enabled:r?.["enabled"]===true};});
export const completeMelhorEnvioConnection=createServerFn({method:"POST"}).validator(z.object({code:z.string().min(1),state:z.string().min(16)})).handler(async({data})=>{const session=await resolveSessionFromRequest();if(!session)throw new Error("Sessão expirada. Entre novamente.");return {returnUrl:await finishMelhorEnvioOAuth(data.code,data.state,session.userId)};});
export const connectMelhorEnvio=createServerFn({method:"POST"}).handler(async()=>{const c=await createMerchantCatalogContext(getRequestHost());return {authorizationUrl:await startMelhorEnvioOAuth(c.scope,c.userId ?? "",getRequestHost())};});
export const saveMelhorEnvioProfile=createServerFn({method:"POST"}).validator(profile).handler(async({data})=>{const c=await createMerchantCatalogContext(getRequestHost());await createAdminSqlExecutor().query(`insert into public.store_shipping_profiles(tenant_id,store_id,postal_code,shipper_name,shipper_email,shipper_phone,document,company_document,state_register,address,number,complement,district,city,state_abbr,enabled) values($1::uuid,$2::uuid,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,upper($15),$16) on conflict(tenant_id,store_id) do update set postal_code=excluded.postal_code,shipper_name=excluded.shipper_name,shipper_email=excluded.shipper_email,shipper_phone=excluded.shipper_phone,document=excluded.document,company_document=excluded.company_document,state_register=excluded.state_register,address=excluded.address,number=excluded.number,complement=excluded.complement,district=excluded.district,city=excluded.city,state_abbr=excluded.state_abbr,enabled=excluded.enabled,updated_at=now()`,[c.scope.tenantId,c.scope.storeId,data.postalCode,data.shipperName,data.shipperEmail,data.shipperPhone,data.document,data.companyDocument,data.stateRegister,data.address,data.number,data.complement,data.district,data.city,data.stateAbbr,data.enabled]);return {ok:true};});

const orderId=z.object({orderId:z.string().uuid()});
export const getOrderShipment=createServerFn({method:"GET"}).validator(orderId).handler(async({data})=>{const c=await createMerchantCatalogContext(getRequestHost());const rows=await createAdminSqlExecutor().query(`select service_name,company_name,quoted_price_cents,quoted_delivery_days,status,provider_shipment_id,label_url,tracking_code from public.order_shipments where tenant_id=$1::uuid and store_id=$2::uuid and order_id=$3::uuid limit 1`,[c.scope.tenantId,c.scope.storeId,data.orderId]);const r=rows[0];if(!r)return null;return{serviceName:typeof r["service_name"]==="string"?r["service_name"]:"",companyName:typeof r["company_name"]==="string"?r["company_name"]:"",quotedPriceCents:Number(r["quoted_price_cents"]??0),quotedDeliveryDays:Number(r["quoted_delivery_days"]??0),status:typeof r["status"]==="string"?r["status"]:"quoted",providerShipmentId:typeof r["provider_shipment_id"]==="string"?r["provider_shipment_id"]:null,labelUrl:typeof r["label_url"]==="string"?r["label_url"]:null,trackingCode:typeof r["tracking_code"]==="string"?r["tracking_code"]:null};});
export const generateOrderShipment=createServerFn({method:"POST"}).validator(orderId).handler(async({data})=>{const c=await createMerchantCatalogContext(getRequestHost());await buyOrderShipment(c.scope,data.orderId);await createAdminSqlExecutor().query(`insert into public.audit_logs(actor_user_id,tenant_id,store_id,action,resource_type,resource_id,metadata) values($1::uuid,$2::uuid,$3::uuid,'shipping.label_generated','order',$4,'{}'::jsonb)`,[c.userId,c.scope.tenantId,c.scope.storeId,data.orderId]);return{ok:true};});
