/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as CatalogRouteImport } from './routes/catalog'
import { Route as ControlRouteImport } from './routes/control'
import { Route as LoginRouteImport } from './routes/login'
import { Route as MasterRouteImport } from './routes/master'
import { Route as MasterIndexRouteImport } from './routes/master.index'
import { Route as MasterAuditRouteImport } from './routes/master.audit'
import { Route as MasterBillingRouteImport } from './routes/master.billing'
import { Route as MasterInfrastructureRouteImport } from './routes/master.infrastructure'
import { Route as MasterPlatformsRouteImport } from './routes/master.platforms'
import { Route as MasterSettingsRouteImport } from './routes/master.settings'
import { Route as MasterSupportRouteImport } from './routes/master.support'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminCampaignsRouteImport } from './routes/admin.campaigns'
import { Route as AdminCategoriesRouteImport } from './routes/admin.categories'
import { Route as AdminCouponsRouteImport } from './routes/admin.coupons'
import { Route as AdminCustomersRouteImport } from './routes/admin.customers'
import { Route as AdminFinanceRouteImport } from './routes/admin.finance'
import { Route as AdminInventoryRouteImport } from './routes/admin.inventory'
import { Route as AdminMarketingRouteImport } from './routes/admin.marketing'
import { Route as AdminOperationsRouteImport } from './routes/admin.operations'
import { Route as AdminOrdersRouteImport } from './routes/admin.orders'
import { Route as AdminProductsRouteImport } from './routes/admin.products'
import { Route as AdminPurchasesRouteImport } from './routes/admin.purchases'
import { Route as AdminSettingsRouteImport } from './routes/admin.settings'
import { Route as AdminStoreRouteImport } from './routes/admin.store'
import { Route as AdminSuppliersRouteImport } from './routes/admin.suppliers'
import { Route as AdminTasksRouteImport } from './routes/admin.tasks'
import { Route as AdminCustomersIndexRouteImport } from './routes/admin.customers.index'
import { Route as AdminCustomersIdRouteImport } from './routes/admin.customers.$id'
import { Route as AdminOrdersIndexRouteImport } from './routes/admin.orders.index'
import { Route as AdminOrdersIdRouteImport } from './routes/admin.orders.$id'
import { Route as AdminProductsIdRouteImport } from './routes/admin.products.$id'
import { Route as AdminProductsNewRouteImport } from './routes/admin.products.new'
import { Route as AdminStoreIndexRouteImport } from './routes/admin.store.index'
import { Route as AdminStoreAppearanceRouteImport } from './routes/admin.store.appearance'
import { Route as AdminStoreBannersRouteImport } from './routes/admin.store.banners'
import { Route as AdminStoreCatalogRouteImport } from './routes/admin.store.catalog'
import { Route as ControlIndexRouteImport } from './routes/control.index'
import { Route as ControlAuditRouteImport } from './routes/control.audit'
import { Route as ControlBillingRouteImport } from './routes/control.billing'
import { Route as ControlBrandingRouteImport } from './routes/control.branding'
import { Route as ControlDomainsRouteImport } from './routes/control.domains'
import { Route as ControlPaymentsRouteImport } from './routes/control.payments'
import { Route as ControlPlansRouteImport } from './routes/control.plans'
import { Route as ControlStoresRouteImport } from './routes/control.stores'
import { Route as ControlTeamRouteImport } from './routes/control.team'
import { Route as ControlStoresStoreIdRouteImport } from './routes/control.stores_.$storeId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const CatalogRoute = CatalogRouteImport.update({
  id: '/catalog',
  path: '/catalog',
  getParentRoute: () => rootRouteImport,
} as any)
const ControlRoute = ControlRouteImport.update({
  id: '/control',
  path: '/control',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const MasterRoute = MasterRouteImport.update({
  id: '/master',
  path: '/master',
  getParentRoute: () => rootRouteImport,
} as any)
const MasterIndexRoute = MasterIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MasterRoute,
} as any)
const MasterAuditRoute = MasterAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => MasterRoute,
} as any)
const MasterBillingRoute = MasterBillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => MasterRoute,
} as any)
const MasterInfrastructureRoute = MasterInfrastructureRouteImport.update({
  id: '/infrastructure',
  path: '/infrastructure',
  getParentRoute: () => MasterRoute,
} as any)
const MasterPlatformsRoute = MasterPlatformsRouteImport.update({
  id: '/platforms',
  path: '/platforms',
  getParentRoute: () => MasterRoute,
} as any)
const MasterSettingsRoute = MasterSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => MasterRoute,
} as any)
const MasterSupportRoute = MasterSupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => MasterRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCampaignsRoute = AdminCampaignsRouteImport.update({
  id: '/campaigns',
  path: '/campaigns',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCategoriesRoute = AdminCategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCouponsRoute = AdminCouponsRouteImport.update({
  id: '/coupons',
  path: '/coupons',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCustomersRoute = AdminCustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => AdminRoute,
} as any)
const AdminFinanceRoute = AdminFinanceRouteImport.update({
  id: '/finance',
  path: '/finance',
  getParentRoute: () => AdminRoute,
} as any)
const AdminInventoryRoute = AdminInventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMarketingRoute = AdminMarketingRouteImport.update({
  id: '/marketing',
  path: '/marketing',
  getParentRoute: () => AdminRoute,
} as any)
const AdminOperationsRoute = AdminOperationsRouteImport.update({
  id: '/operations',
  path: '/operations',
  getParentRoute: () => AdminRoute,
} as any)
const AdminOrdersRoute = AdminOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProductsRoute = AdminProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPurchasesRoute = AdminPurchasesRouteImport.update({
  id: '/purchases',
  path: '/purchases',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminStoreRoute = AdminStoreRouteImport.update({
  id: '/store',
  path: '/store',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSuppliersRoute = AdminSuppliersRouteImport.update({
  id: '/suppliers',
  path: '/suppliers',
  getParentRoute: () => AdminRoute,
} as any)
const AdminTasksRoute = AdminTasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCustomersIndexRoute = AdminCustomersIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminCustomersRoute,
} as any)
const AdminCustomersIdRoute = AdminCustomersIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AdminCustomersRoute,
} as any)
const AdminOrdersIndexRoute = AdminOrdersIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminOrdersRoute,
} as any)
const AdminOrdersIdRoute = AdminOrdersIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AdminOrdersRoute,
} as any)
const AdminProductsIdRoute = AdminProductsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AdminProductsRoute,
} as any)
const AdminProductsNewRoute = AdminProductsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AdminProductsRoute,
} as any)
const AdminStoreIndexRoute = AdminStoreIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminStoreRoute,
} as any)
const AdminStoreAppearanceRoute = AdminStoreAppearanceRouteImport.update({
  id: '/appearance',
  path: '/appearance',
  getParentRoute: () => AdminStoreRoute,
} as any)
const AdminStoreBannersRoute = AdminStoreBannersRouteImport.update({
  id: '/banners',
  path: '/banners',
  getParentRoute: () => AdminStoreRoute,
} as any)
const AdminStoreCatalogRoute = AdminStoreCatalogRouteImport.update({
  id: '/catalog',
  path: '/catalog',
  getParentRoute: () => AdminStoreRoute,
} as any)
const ControlIndexRoute = ControlIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ControlRoute,
} as any)
const ControlAuditRoute = ControlAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => ControlRoute,
} as any)
const ControlBillingRoute = ControlBillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => ControlRoute,
} as any)
const ControlBrandingRoute = ControlBrandingRouteImport.update({
  id: '/branding',
  path: '/branding',
  getParentRoute: () => ControlRoute,
} as any)
const ControlDomainsRoute = ControlDomainsRouteImport.update({
  id: '/domains',
  path: '/domains',
  getParentRoute: () => ControlRoute,
} as any)
const ControlPaymentsRoute = ControlPaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => ControlRoute,
} as any)
const ControlPlansRoute = ControlPlansRouteImport.update({
  id: '/plans',
  path: '/plans',
  getParentRoute: () => ControlRoute,
} as any)
const ControlStoresRoute = ControlStoresRouteImport.update({
  id: '/stores',
  path: '/stores',
  getParentRoute: () => ControlRoute,
} as any)
const ControlTeamRoute = ControlTeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => ControlRoute,
} as any)
const ControlStoresStoreIdRoute = ControlStoresStoreIdRouteImport.update({
  id: '/stores_/$storeId',
  path: '/stores/$storeId',
  getParentRoute: () => ControlRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/catalog': typeof CatalogRoute
  '/control': typeof ControlRouteWithChildren
  '/login': typeof LoginRoute
  '/master': typeof MasterRouteWithChildren
  '/master/': typeof MasterIndexRoute
  '/master/audit': typeof MasterAuditRoute
  '/master/billing': typeof MasterBillingRoute
  '/master/infrastructure': typeof MasterInfrastructureRoute
  '/master/platforms': typeof MasterPlatformsRoute
  '/master/settings': typeof MasterSettingsRoute
  '/master/support': typeof MasterSupportRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/campaigns': typeof AdminCampaignsRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/coupons': typeof AdminCouponsRoute
  '/admin/customers': typeof AdminCustomersRouteWithChildren
  '/admin/finance': typeof AdminFinanceRoute
  '/admin/inventory': typeof AdminInventoryRoute
  '/admin/marketing': typeof AdminMarketingRoute
  '/admin/operations': typeof AdminOperationsRoute
  '/admin/orders': typeof AdminOrdersRouteWithChildren
  '/admin/products': typeof AdminProductsRouteWithChildren
  '/admin/purchases': typeof AdminPurchasesRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/store': typeof AdminStoreRouteWithChildren
  '/admin/suppliers': typeof AdminSuppliersRoute
  '/admin/tasks': typeof AdminTasksRoute
  '/admin/customers/': typeof AdminCustomersIndexRoute
  '/admin/customers/$id': typeof AdminCustomersIdRoute
  '/admin/orders/': typeof AdminOrdersIndexRoute
  '/admin/orders/$id': typeof AdminOrdersIdRoute
  '/admin/products/$id': typeof AdminProductsIdRoute
  '/admin/products/new': typeof AdminProductsNewRoute
  '/admin/store/': typeof AdminStoreIndexRoute
  '/admin/store/appearance': typeof AdminStoreAppearanceRoute
  '/admin/store/banners': typeof AdminStoreBannersRoute
  '/admin/store/catalog': typeof AdminStoreCatalogRoute
  '/control/': typeof ControlIndexRoute
  '/control/audit': typeof ControlAuditRoute
  '/control/billing': typeof ControlBillingRoute
  '/control/branding': typeof ControlBrandingRoute
  '/control/domains': typeof ControlDomainsRoute
  '/control/payments': typeof ControlPaymentsRoute
  '/control/plans': typeof ControlPlansRoute
  '/control/stores': typeof ControlStoresRoute
  '/control/team': typeof ControlTeamRoute
  '/control/stores/$storeId': typeof ControlStoresStoreIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminIndexRoute
  '/catalog': typeof CatalogRoute
  '/control': typeof ControlIndexRoute
  '/login': typeof LoginRoute
  '/master': typeof MasterIndexRoute
  '/master/audit': typeof MasterAuditRoute
  '/master/billing': typeof MasterBillingRoute
  '/master/infrastructure': typeof MasterInfrastructureRoute
  '/master/platforms': typeof MasterPlatformsRoute
  '/master/settings': typeof MasterSettingsRoute
  '/master/support': typeof MasterSupportRoute
  '/admin/campaigns': typeof AdminCampaignsRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/coupons': typeof AdminCouponsRoute
  '/admin/customers': typeof AdminCustomersIndexRoute
  '/admin/finance': typeof AdminFinanceRoute
  '/admin/inventory': typeof AdminInventoryRoute
  '/admin/marketing': typeof AdminMarketingRoute
  '/admin/operations': typeof AdminOperationsRoute
  '/admin/orders': typeof AdminOrdersIndexRoute
  '/admin/products': typeof AdminProductsRouteWithChildren
  '/admin/purchases': typeof AdminPurchasesRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/store': typeof AdminStoreIndexRoute
  '/admin/suppliers': typeof AdminSuppliersRoute
  '/admin/tasks': typeof AdminTasksRoute
  '/admin/customers/$id': typeof AdminCustomersIdRoute
  '/admin/orders/$id': typeof AdminOrdersIdRoute
  '/admin/products/$id': typeof AdminProductsIdRoute
  '/admin/products/new': typeof AdminProductsNewRoute
  '/admin/store/appearance': typeof AdminStoreAppearanceRoute
  '/admin/store/banners': typeof AdminStoreBannersRoute
  '/admin/store/catalog': typeof AdminStoreCatalogRoute
  '/control/audit': typeof ControlAuditRoute
  '/control/billing': typeof ControlBillingRoute
  '/control/branding': typeof ControlBrandingRoute
  '/control/domains': typeof ControlDomainsRoute
  '/control/payments': typeof ControlPaymentsRoute
  '/control/plans': typeof ControlPlansRoute
  '/control/stores': typeof ControlStoresRoute
  '/control/team': typeof ControlTeamRoute
  '/control/stores/$storeId': typeof ControlStoresStoreIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/catalog': typeof CatalogRoute
  '/control': typeof ControlRouteWithChildren
  '/login': typeof LoginRoute
  '/master': typeof MasterRouteWithChildren
  '/master/': typeof MasterIndexRoute
  '/master/audit': typeof MasterAuditRoute
  '/master/billing': typeof MasterBillingRoute
  '/master/infrastructure': typeof MasterInfrastructureRoute
  '/master/platforms': typeof MasterPlatformsRoute
  '/master/settings': typeof MasterSettingsRoute
  '/master/support': typeof MasterSupportRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/campaigns': typeof AdminCampaignsRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/coupons': typeof AdminCouponsRoute
  '/admin/customers': typeof AdminCustomersRouteWithChildren
  '/admin/finance': typeof AdminFinanceRoute
  '/admin/inventory': typeof AdminInventoryRoute
  '/admin/marketing': typeof AdminMarketingRoute
  '/admin/operations': typeof AdminOperationsRoute
  '/admin/orders': typeof AdminOrdersRouteWithChildren
  '/admin/products': typeof AdminProductsRouteWithChildren
  '/admin/purchases': typeof AdminPurchasesRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/store': typeof AdminStoreRouteWithChildren
  '/admin/suppliers': typeof AdminSuppliersRoute
  '/admin/tasks': typeof AdminTasksRoute
  '/admin/customers/': typeof AdminCustomersIndexRoute
  '/admin/customers/$id': typeof AdminCustomersIdRoute
  '/admin/orders/': typeof AdminOrdersIndexRoute
  '/admin/orders/$id': typeof AdminOrdersIdRoute
  '/admin/products/$id': typeof AdminProductsIdRoute
  '/admin/products/new': typeof AdminProductsNewRoute
  '/admin/store/': typeof AdminStoreIndexRoute
  '/admin/store/appearance': typeof AdminStoreAppearanceRoute
  '/admin/store/banners': typeof AdminStoreBannersRoute
  '/admin/store/catalog': typeof AdminStoreCatalogRoute
  '/control/': typeof ControlIndexRoute
  '/control/audit': typeof ControlAuditRoute
  '/control/billing': typeof ControlBillingRoute
  '/control/branding': typeof ControlBrandingRoute
  '/control/domains': typeof ControlDomainsRoute
  '/control/payments': typeof ControlPaymentsRoute
  '/control/plans': typeof ControlPlansRoute
  '/control/stores': typeof ControlStoresRoute
  '/control/team': typeof ControlTeamRoute
  '/control/stores_/$storeId': typeof ControlStoresStoreIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/catalog'
    | '/control'
    | '/login'
    | '/master'
    | '/master/'
    | '/master/audit'
    | '/master/billing'
    | '/master/infrastructure'
    | '/master/platforms'
    | '/master/settings'
    | '/master/support'
    | '/admin/'
    | '/admin/campaigns'
    | '/admin/categories'
    | '/admin/coupons'
    | '/admin/customers'
    | '/admin/finance'
    | '/admin/inventory'
    | '/admin/marketing'
    | '/admin/operations'
    | '/admin/orders'
    | '/admin/products'
    | '/admin/purchases'
    | '/admin/settings'
    | '/admin/store'
    | '/admin/suppliers'
    | '/admin/tasks'
    | '/admin/customers/'
    | '/admin/customers/$id'
    | '/admin/orders/'
    | '/admin/orders/$id'
    | '/admin/products/$id'
    | '/admin/products/new'
    | '/admin/store/'
    | '/admin/store/appearance'
    | '/admin/store/banners'
    | '/admin/store/catalog'
    | '/control/'
    | '/control/audit'
    | '/control/billing'
    | '/control/branding'
    | '/control/domains'
    | '/control/payments'
    | '/control/plans'
    | '/control/stores'
    | '/control/team'
    | '/control/stores/$storeId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/catalog'
    | '/control'
    | '/login'
    | '/master'
    | '/master/audit'
    | '/master/billing'
    | '/master/infrastructure'
    | '/master/platforms'
    | '/master/settings'
    | '/master/support'
    | '/admin/campaigns'
    | '/admin/categories'
    | '/admin/coupons'
    | '/admin/customers'
    | '/admin/finance'
    | '/admin/inventory'
    | '/admin/marketing'
    | '/admin/operations'
    | '/admin/orders'
    | '/admin/products'
    | '/admin/purchases'
    | '/admin/settings'
    | '/admin/store'
    | '/admin/suppliers'
    | '/admin/tasks'
    | '/admin/customers/$id'
    | '/admin/orders/$id'
    | '/admin/products/$id'
    | '/admin/products/new'
    | '/admin/store/appearance'
    | '/admin/store/banners'
    | '/admin/store/catalog'
    | '/control/audit'
    | '/control/billing'
    | '/control/branding'
    | '/control/domains'
    | '/control/payments'
    | '/control/plans'
    | '/control/stores'
    | '/control/team'
    | '/control/stores/$storeId'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/catalog'
    | '/control'
    | '/login'
    | '/master'
    | '/master/'
    | '/master/audit'
    | '/master/billing'
    | '/master/infrastructure'
    | '/master/platforms'
    | '/master/settings'
    | '/master/support'
    | '/admin/'
    | '/admin/campaigns'
    | '/admin/categories'
    | '/admin/coupons'
    | '/admin/customers'
    | '/admin/finance'
    | '/admin/inventory'
    | '/admin/marketing'
    | '/admin/operations'
    | '/admin/orders'
    | '/admin/products'
    | '/admin/purchases'
    | '/admin/settings'
    | '/admin/store'
    | '/admin/suppliers'
    | '/admin/tasks'
    | '/admin/customers/'
    | '/admin/customers/$id'
    | '/admin/orders/'
    | '/admin/orders/$id'
    | '/admin/products/$id'
    | '/admin/products/new'
    | '/admin/store/'
    | '/admin/store/appearance'
    | '/admin/store/banners'
    | '/admin/store/catalog'
    | '/control/'
    | '/control/audit'
    | '/control/billing'
    | '/control/branding'
    | '/control/domains'
    | '/control/payments'
    | '/control/plans'
    | '/control/stores'
    | '/control/team'
    | '/control/stores_/$storeId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  CatalogRoute: typeof CatalogRoute
  ControlRoute: typeof ControlRouteWithChildren
  LoginRoute: typeof LoginRoute
  MasterRoute: typeof MasterRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/catalog': {
      id: '/catalog'
      path: '/catalog'
      fullPath: '/catalog'
      preLoaderRoute: typeof CatalogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/control': {
      id: '/control'
      path: '/control'
      fullPath: '/control'
      preLoaderRoute: typeof ControlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/master': {
      id: '/master'
      path: '/master'
      fullPath: '/master'
      preLoaderRoute: typeof MasterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/master/': {
      id: '/master/'
      path: '/'
      fullPath: '/master/'
      preLoaderRoute: typeof MasterIndexRouteImport
      parentRoute: typeof MasterRoute
    }
    '/master/audit': {
      id: '/master/audit'
      path: '/audit'
      fullPath: '/master/audit'
      preLoaderRoute: typeof MasterAuditRouteImport
      parentRoute: typeof MasterRoute
    }
    '/master/billing': {
      id: '/master/billing'
      path: '/billing'
      fullPath: '/master/billing'
      preLoaderRoute: typeof MasterBillingRouteImport
      parentRoute: typeof MasterRoute
    }
    '/master/infrastructure': {
      id: '/master/infrastructure'
      path: '/infrastructure'
      fullPath: '/master/infrastructure'
      preLoaderRoute: typeof MasterInfrastructureRouteImport
      parentRoute: typeof MasterRoute
    }
    '/master/platforms': {
      id: '/master/platforms'
      path: '/platforms'
      fullPath: '/master/platforms'
      preLoaderRoute: typeof MasterPlatformsRouteImport
      parentRoute: typeof MasterRoute
    }
    '/master/settings': {
      id: '/master/settings'
      path: '/settings'
      fullPath: '/master/settings'
      preLoaderRoute: typeof MasterSettingsRouteImport
      parentRoute: typeof MasterRoute
    }
    '/master/support': {
      id: '/master/support'
      path: '/support'
      fullPath: '/master/support'
      preLoaderRoute: typeof MasterSupportRouteImport
      parentRoute: typeof MasterRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/campaigns': {
      id: '/admin/campaigns'
      path: '/campaigns'
      fullPath: '/admin/campaigns'
      preLoaderRoute: typeof AdminCampaignsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/categories': {
      id: '/admin/categories'
      path: '/categories'
      fullPath: '/admin/categories'
      preLoaderRoute: typeof AdminCategoriesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/coupons': {
      id: '/admin/coupons'
      path: '/coupons'
      fullPath: '/admin/coupons'
      preLoaderRoute: typeof AdminCouponsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/customers': {
      id: '/admin/customers'
      path: '/customers'
      fullPath: '/admin/customers'
      preLoaderRoute: typeof AdminCustomersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/finance': {
      id: '/admin/finance'
      path: '/finance'
      fullPath: '/admin/finance'
      preLoaderRoute: typeof AdminFinanceRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/inventory': {
      id: '/admin/inventory'
      path: '/inventory'
      fullPath: '/admin/inventory'
      preLoaderRoute: typeof AdminInventoryRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/marketing': {
      id: '/admin/marketing'
      path: '/marketing'
      fullPath: '/admin/marketing'
      preLoaderRoute: typeof AdminMarketingRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/operations': {
      id: '/admin/operations'
      path: '/operations'
      fullPath: '/admin/operations'
      preLoaderRoute: typeof AdminOperationsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/orders': {
      id: '/admin/orders'
      path: '/orders'
      fullPath: '/admin/orders'
      preLoaderRoute: typeof AdminOrdersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/products': {
      id: '/admin/products'
      path: '/products'
      fullPath: '/admin/products'
      preLoaderRoute: typeof AdminProductsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/purchases': {
      id: '/admin/purchases'
      path: '/purchases'
      fullPath: '/admin/purchases'
      preLoaderRoute: typeof AdminPurchasesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/store': {
      id: '/admin/store'
      path: '/store'
      fullPath: '/admin/store'
      preLoaderRoute: typeof AdminStoreRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/suppliers': {
      id: '/admin/suppliers'
      path: '/suppliers'
      fullPath: '/admin/suppliers'
      preLoaderRoute: typeof AdminSuppliersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/tasks': {
      id: '/admin/tasks'
      path: '/tasks'
      fullPath: '/admin/tasks'
      preLoaderRoute: typeof AdminTasksRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/customers/': {
      id: '/admin/customers/'
      path: '/'
      fullPath: '/admin/customers/'
      preLoaderRoute: typeof AdminCustomersIndexRouteImport
      parentRoute: typeof AdminCustomersRoute
    }
    '/admin/customers/$id': {
      id: '/admin/customers/$id'
      path: '/$id'
      fullPath: '/admin/customers/$id'
      preLoaderRoute: typeof AdminCustomersIdRouteImport
      parentRoute: typeof AdminCustomersRoute
    }
    '/admin/orders/': {
      id: '/admin/orders/'
      path: '/'
      fullPath: '/admin/orders/'
      preLoaderRoute: typeof AdminOrdersIndexRouteImport
      parentRoute: typeof AdminOrdersRoute
    }
    '/admin/orders/$id': {
      id: '/admin/orders/$id'
      path: '/$id'
      fullPath: '/admin/orders/$id'
      preLoaderRoute: typeof AdminOrdersIdRouteImport
      parentRoute: typeof AdminOrdersRoute
    }
    '/admin/products/$id': {
      id: '/admin/products/$id'
      path: '/$id'
      fullPath: '/admin/products/$id'
      preLoaderRoute: typeof AdminProductsIdRouteImport
      parentRoute: typeof AdminProductsRoute
    }
    '/admin/products/new': {
      id: '/admin/products/new'
      path: '/new'
      fullPath: '/admin/products/new'
      preLoaderRoute: typeof AdminProductsNewRouteImport
      parentRoute: typeof AdminProductsRoute
    }
    '/admin/store/': {
      id: '/admin/store/'
      path: '/'
      fullPath: '/admin/store/'
      preLoaderRoute: typeof AdminStoreIndexRouteImport
      parentRoute: typeof AdminStoreRoute
    }
    '/admin/store/appearance': {
      id: '/admin/store/appearance'
      path: '/appearance'
      fullPath: '/admin/store/appearance'
      preLoaderRoute: typeof AdminStoreAppearanceRouteImport
      parentRoute: typeof AdminStoreRoute
    }
    '/admin/store/banners': {
      id: '/admin/store/banners'
      path: '/banners'
      fullPath: '/admin/store/banners'
      preLoaderRoute: typeof AdminStoreBannersRouteImport
      parentRoute: typeof AdminStoreRoute
    }
    '/admin/store/catalog': {
      id: '/admin/store/catalog'
      path: '/catalog'
      fullPath: '/admin/store/catalog'
      preLoaderRoute: typeof AdminStoreCatalogRouteImport
      parentRoute: typeof AdminStoreRoute
    }
    '/control/': {
      id: '/control/'
      path: '/'
      fullPath: '/control/'
      preLoaderRoute: typeof ControlIndexRouteImport
      parentRoute: typeof ControlRoute
    }
    '/control/audit': {
      id: '/control/audit'
      path: '/audit'
      fullPath: '/control/audit'
      preLoaderRoute: typeof ControlAuditRouteImport
      parentRoute: typeof ControlRoute
    }
    '/control/billing': {
      id: '/control/billing'
      path: '/billing'
      fullPath: '/control/billing'
      preLoaderRoute: typeof ControlBillingRouteImport
      parentRoute: typeof ControlRoute
    }
    '/control/branding': {
      id: '/control/branding'
      path: '/branding'
      fullPath: '/control/branding'
      preLoaderRoute: typeof ControlBrandingRouteImport
      parentRoute: typeof ControlRoute
    }
    '/control/domains': {
      id: '/control/domains'
      path: '/domains'
      fullPath: '/control/domains'
      preLoaderRoute: typeof ControlDomainsRouteImport
      parentRoute: typeof ControlRoute
    }
    '/control/payments': {
      id: '/control/payments'
      path: '/payments'
      fullPath: '/control/payments'
      preLoaderRoute: typeof ControlPaymentsRouteImport
      parentRoute: typeof ControlRoute
    }
    '/control/plans': {
      id: '/control/plans'
      path: '/plans'
      fullPath: '/control/plans'
      preLoaderRoute: typeof ControlPlansRouteImport
      parentRoute: typeof ControlRoute
    }
    '/control/stores': {
      id: '/control/stores'
      path: '/stores'
      fullPath: '/control/stores'
      preLoaderRoute: typeof ControlStoresRouteImport
      parentRoute: typeof ControlRoute
    }
    '/control/team': {
      id: '/control/team'
      path: '/team'
      fullPath: '/control/team'
      preLoaderRoute: typeof ControlTeamRouteImport
      parentRoute: typeof ControlRoute
    }
    '/control/stores_/$storeId': {
      id: '/control/stores_/$storeId'
      path: '/stores/$storeId'
      fullPath: '/control/stores/$storeId'
      preLoaderRoute: typeof ControlStoresStoreIdRouteImport
      parentRoute: typeof ControlRoute
    }
  }
}

interface AdminCustomersRouteChildren {
  AdminCustomersIndexRoute: typeof AdminCustomersIndexRoute
  AdminCustomersIdRoute: typeof AdminCustomersIdRoute
}

const AdminCustomersRouteChildren: AdminCustomersRouteChildren = {
  AdminCustomersIndexRoute: AdminCustomersIndexRoute,
  AdminCustomersIdRoute: AdminCustomersIdRoute,
}

const AdminCustomersRouteWithChildren = AdminCustomersRoute._addFileChildren(AdminCustomersRouteChildren)

interface AdminOrdersRouteChildren {
  AdminOrdersIndexRoute: typeof AdminOrdersIndexRoute
  AdminOrdersIdRoute: typeof AdminOrdersIdRoute
}

const AdminOrdersRouteChildren: AdminOrdersRouteChildren = {
  AdminOrdersIndexRoute: AdminOrdersIndexRoute,
  AdminOrdersIdRoute: AdminOrdersIdRoute,
}

const AdminOrdersRouteWithChildren = AdminOrdersRoute._addFileChildren(AdminOrdersRouteChildren)

interface AdminProductsRouteChildren {
  AdminProductsIdRoute: typeof AdminProductsIdRoute
  AdminProductsNewRoute: typeof AdminProductsNewRoute
}

const AdminProductsRouteChildren: AdminProductsRouteChildren = {
  AdminProductsIdRoute: AdminProductsIdRoute,
  AdminProductsNewRoute: AdminProductsNewRoute,
}

const AdminProductsRouteWithChildren = AdminProductsRoute._addFileChildren(AdminProductsRouteChildren)

interface AdminStoreRouteChildren {
  AdminStoreIndexRoute: typeof AdminStoreIndexRoute
  AdminStoreAppearanceRoute: typeof AdminStoreAppearanceRoute
  AdminStoreBannersRoute: typeof AdminStoreBannersRoute
  AdminStoreCatalogRoute: typeof AdminStoreCatalogRoute
}

const AdminStoreRouteChildren: AdminStoreRouteChildren = {
  AdminStoreIndexRoute: AdminStoreIndexRoute,
  AdminStoreAppearanceRoute: AdminStoreAppearanceRoute,
  AdminStoreBannersRoute: AdminStoreBannersRoute,
  AdminStoreCatalogRoute: AdminStoreCatalogRoute,
}

const AdminStoreRouteWithChildren = AdminStoreRoute._addFileChildren(AdminStoreRouteChildren)

interface AdminRouteChildren {
  AdminIndexRoute: typeof AdminIndexRoute
  AdminCampaignsRoute: typeof AdminCampaignsRoute
  AdminCategoriesRoute: typeof AdminCategoriesRoute
  AdminCouponsRoute: typeof AdminCouponsRoute
  AdminCustomersRoute: typeof AdminCustomersRouteWithChildren
  AdminFinanceRoute: typeof AdminFinanceRoute
  AdminInventoryRoute: typeof AdminInventoryRoute
  AdminMarketingRoute: typeof AdminMarketingRoute
  AdminOperationsRoute: typeof AdminOperationsRoute
  AdminOrdersRoute: typeof AdminOrdersRouteWithChildren
  AdminProductsRoute: typeof AdminProductsRouteWithChildren
  AdminPurchasesRoute: typeof AdminPurchasesRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminStoreRoute: typeof AdminStoreRouteWithChildren
  AdminSuppliersRoute: typeof AdminSuppliersRoute
  AdminTasksRoute: typeof AdminTasksRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminIndexRoute: AdminIndexRoute,
  AdminCampaignsRoute: AdminCampaignsRoute,
  AdminCategoriesRoute: AdminCategoriesRoute,
  AdminCouponsRoute: AdminCouponsRoute,
  AdminCustomersRoute: AdminCustomersRouteWithChildren,
  AdminFinanceRoute: AdminFinanceRoute,
  AdminInventoryRoute: AdminInventoryRoute,
  AdminMarketingRoute: AdminMarketingRoute,
  AdminOperationsRoute: AdminOperationsRoute,
  AdminOrdersRoute: AdminOrdersRouteWithChildren,
  AdminProductsRoute: AdminProductsRouteWithChildren,
  AdminPurchasesRoute: AdminPurchasesRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminStoreRoute: AdminStoreRouteWithChildren,
  AdminSuppliersRoute: AdminSuppliersRoute,
  AdminTasksRoute: AdminTasksRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface ControlRouteChildren {
  ControlIndexRoute: typeof ControlIndexRoute
  ControlAuditRoute: typeof ControlAuditRoute
  ControlBillingRoute: typeof ControlBillingRoute
  ControlBrandingRoute: typeof ControlBrandingRoute
  ControlDomainsRoute: typeof ControlDomainsRoute
  ControlPaymentsRoute: typeof ControlPaymentsRoute
  ControlPlansRoute: typeof ControlPlansRoute
  ControlStoresRoute: typeof ControlStoresRoute
  ControlTeamRoute: typeof ControlTeamRoute
  ControlStoresStoreIdRoute: typeof ControlStoresStoreIdRoute
}

const ControlRouteChildren: ControlRouteChildren = {
  ControlIndexRoute: ControlIndexRoute,
  ControlAuditRoute: ControlAuditRoute,
  ControlBillingRoute: ControlBillingRoute,
  ControlBrandingRoute: ControlBrandingRoute,
  ControlDomainsRoute: ControlDomainsRoute,
  ControlPaymentsRoute: ControlPaymentsRoute,
  ControlPlansRoute: ControlPlansRoute,
  ControlStoresRoute: ControlStoresRoute,
  ControlTeamRoute: ControlTeamRoute,
  ControlStoresStoreIdRoute: ControlStoresStoreIdRoute,
}

const ControlRouteWithChildren = ControlRoute._addFileChildren(ControlRouteChildren)

interface MasterRouteChildren {
  MasterIndexRoute: typeof MasterIndexRoute
  MasterAuditRoute: typeof MasterAuditRoute
  MasterBillingRoute: typeof MasterBillingRoute
  MasterInfrastructureRoute: typeof MasterInfrastructureRoute
  MasterPlatformsRoute: typeof MasterPlatformsRoute
  MasterSettingsRoute: typeof MasterSettingsRoute
  MasterSupportRoute: typeof MasterSupportRoute
}

const MasterRouteChildren: MasterRouteChildren = {
  MasterIndexRoute: MasterIndexRoute,
  MasterAuditRoute: MasterAuditRoute,
  MasterBillingRoute: MasterBillingRoute,
  MasterInfrastructureRoute: MasterInfrastructureRoute,
  MasterPlatformsRoute: MasterPlatformsRoute,
  MasterSettingsRoute: MasterSettingsRoute,
  MasterSupportRoute: MasterSupportRoute,
}

const MasterRouteWithChildren = MasterRoute._addFileChildren(MasterRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  CatalogRoute: CatalogRoute,
  ControlRoute: ControlRouteWithChildren,
  LoginRoute: LoginRoute,
  MasterRoute: MasterRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
