/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as CatalogRouteImport } from './routes/catalog'
import { Route as ControlRouteImport } from './routes/control'
import { Route as LoginRouteImport } from './routes/login'
import { Route as MasterIndexRouteImport } from './routes/master/index'
import { Route as Master_layoutRouteImport } from './routes/master/__layout'
import { Route as MasterAuditRouteImport } from './routes/master/audit'
import { Route as MasterBillingRouteImport } from './routes/master/billing'
import { Route as MasterInfrastructureRouteImport } from './routes/master/infrastructure'
import { Route as MasterPlatformsRouteImport } from './routes/master/platforms'
import { Route as MasterSettingsRouteImport } from './routes/master/settings'
import { Route as MasterSupportRouteImport } from './routes/master/support'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const CatalogRoute = CatalogRouteImport.update({
  id: '/catalog',
  path: '/catalog',
  getParentRoute: () => rootRouteImport,
} as any)
const ControlRoute = ControlRouteImport.update({
  id: '/control',
  path: '/control',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const MasterIndexRoute = MasterIndexRouteImport.update({
  id: '/master/',
  path: '/master/',
  getParentRoute: () => rootRouteImport,
} as any)
const Master_layoutRoute = Master_layoutRouteImport.update({
  id: '/master/__layout',
  path: '/master',
  getParentRoute: () => rootRouteImport,
} as any)
const MasterAuditRoute = MasterAuditRouteImport.update({
  id: '/master/audit',
  path: '/master/audit',
  getParentRoute: () => rootRouteImport,
} as any)
const MasterBillingRoute = MasterBillingRouteImport.update({
  id: '/master/billing',
  path: '/master/billing',
  getParentRoute: () => rootRouteImport,
} as any)
const MasterInfrastructureRoute = MasterInfrastructureRouteImport.update({
  id: '/master/infrastructure',
  path: '/master/infrastructure',
  getParentRoute: () => rootRouteImport,
} as any)
const MasterPlatformsRoute = MasterPlatformsRouteImport.update({
  id: '/master/platforms',
  path: '/master/platforms',
  getParentRoute: () => rootRouteImport,
} as any)
const MasterSettingsRoute = MasterSettingsRouteImport.update({
  id: '/master/settings',
  path: '/master/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const MasterSupportRoute = MasterSupportRouteImport.update({
  id: '/master/support',
  path: '/master/support',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/catalog': typeof CatalogRoute
  '/control': typeof ControlRoute
  '/login': typeof LoginRoute
  '/master': typeof Master_layoutRoute
  '/master/audit': typeof MasterAuditRoute
  '/master/billing': typeof MasterBillingRoute
  '/master/infrastructure': typeof MasterInfrastructureRoute
  '/master/platforms': typeof MasterPlatformsRoute
  '/master/settings': typeof MasterSettingsRoute
  '/master/support': typeof MasterSupportRoute
  '/master/': typeof MasterIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/catalog': typeof CatalogRoute
  '/control': typeof ControlRoute
  '/login': typeof LoginRoute
  '/master': typeof MasterIndexRoute
  '/master/audit': typeof MasterAuditRoute
  '/master/billing': typeof MasterBillingRoute
  '/master/infrastructure': typeof MasterInfrastructureRoute
  '/master/platforms': typeof MasterPlatformsRoute
  '/master/settings': typeof MasterSettingsRoute
  '/master/support': typeof MasterSupportRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/catalog': typeof CatalogRoute
  '/control': typeof ControlRoute
  '/login': typeof LoginRoute
  '/master/__layout': typeof Master_layoutRoute
  '/master/audit': typeof MasterAuditRoute
  '/master/billing': typeof MasterBillingRoute
  '/master/infrastructure': typeof MasterInfrastructureRoute
  '/master/platforms': typeof MasterPlatformsRoute
  '/master/settings': typeof MasterSettingsRoute
  '/master/support': typeof MasterSupportRoute
  '/master/': typeof MasterIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/catalog'
    | '/control'
    | '/login'
    | '/master'
    | '/master/audit'
    | '/master/billing'
    | '/master/infrastructure'
    | '/master/platforms'
    | '/master/settings'
    | '/master/support'
    | '/master/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/catalog'
    | '/control'
    | '/login'
    | '/master'
    | '/master/audit'
    | '/master/billing'
    | '/master/infrastructure'
    | '/master/platforms'
    | '/master/settings'
    | '/master/support'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/catalog'
    | '/control'
    | '/login'
    | '/master/__layout'
    | '/master/audit'
    | '/master/billing'
    | '/master/infrastructure'
    | '/master/platforms'
    | '/master/settings'
    | '/master/support'
    | '/master/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  CatalogRoute: typeof CatalogRoute
  ControlRoute: typeof ControlRoute
  LoginRoute: typeof LoginRoute
  Master_layoutRoute: typeof Master_layoutRoute
  MasterAuditRoute: typeof MasterAuditRoute
  MasterBillingRoute: typeof MasterBillingRoute
  MasterInfrastructureRoute: typeof MasterInfrastructureRoute
  MasterPlatformsRoute: typeof MasterPlatformsRoute
  MasterSettingsRoute: typeof MasterSettingsRoute
  MasterSupportRoute: typeof MasterSupportRoute
  MasterIndexRoute: typeof MasterIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/catalog': {
      id: '/catalog'
      path: '/catalog'
      fullPath: '/catalog'
      preLoaderRoute: typeof CatalogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/control': {
      id: '/control'
      path: '/control'
      fullPath: '/control'
      preLoaderRoute: typeof ControlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/master/': {
      id: '/master/'
      path: '/master'
      fullPath: '/master/'
      preLoaderRoute: typeof MasterIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/master/__layout': {
      id: '/master/__layout'
      path: '/master'
      fullPath: '/master'
      preLoaderRoute: typeof Master_layoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/master/audit': {
      id: '/master/audit'
      path: '/master/audit'
      fullPath: '/master/audit'
      preLoaderRoute: typeof MasterAuditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/master/billing': {
      id: '/master/billing'
      path: '/master/billing'
      fullPath: '/master/billing'
      preLoaderRoute: typeof MasterBillingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/master/infrastructure': {
      id: '/master/infrastructure'
      path: '/master/infrastructure'
      fullPath: '/master/infrastructure'
      preLoaderRoute: typeof MasterInfrastructureRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/master/platforms': {
      id: '/master/platforms'
      path: '/master/platforms'
      fullPath: '/master/platforms'
      preLoaderRoute: typeof MasterPlatformsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/master/settings': {
      id: '/master/settings'
      path: '/master/settings'
      fullPath: '/master/settings'
      preLoaderRoute: typeof MasterSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/master/support': {
      id: '/master/support'
      path: '/master/support'
      fullPath: '/master/support'
      preLoaderRoute: typeof MasterSupportRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  CatalogRoute: CatalogRoute,
  ControlRoute: ControlRoute,
  LoginRoute: LoginRoute,
  Master_layoutRoute: Master_layoutRoute,
  MasterAuditRoute: MasterAuditRoute,
  MasterBillingRoute: MasterBillingRoute,
  MasterInfrastructureRoute: MasterInfrastructureRoute,
  MasterPlatformsRoute: MasterPlatformsRoute,
  MasterSettingsRoute: MasterSettingsRoute,
  MasterSupportRoute: MasterSupportRoute,
  MasterIndexRoute: MasterIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
