import { chromium, expect } from "@playwright/test";
import { spawn } from "node:child_process";
import { once } from "node:events";
import { fileURLToPath } from "node:url";
const root=fileURLToPath(new URL("../../",import.meta.url));
const server=spawn(process.execPath,["node_modules/vite/bin/vite.js","--config","tests/browser-fixture/vite.config.mjs"],{cwd:root,stdio:["ignore","pipe","pipe"]});
let ready=false;
await new Promise((resolve,reject)=>{
  const timeout=setTimeout(()=>reject(new Error("Vite não iniciou")),15000);
  server.stdout.on("data",chunk=>{if(String(chunk).includes("Local:")){clearTimeout(timeout);ready=true;resolve();}});
  server.stderr.on("data",chunk=>{if(!ready)process.stderr.write(chunk);});
  server.on("exit",code=>{if(!ready){clearTimeout(timeout);reject(new Error(`Vite terminou: ${code}`));}});
});
let browser;let page;
try {
  browser=await chromium.launch({executablePath:process.env.KATALUU_CHROMIUM_PATH||undefined,args:process.env.KATALUU_CHROMIUM_PATH?["--no-sandbox","--single-process","--no-zygote","--use-gl=angle","--use-angle=swiftshader","--enable-unsafe-swiftshader"]:[]});
  page=await browser.newPage();const errors=[];page.on("pageerror",e=>errors.push(e.message));
  await page.goto("http://127.0.0.1:5188");
  await page.getByLabel("Nome *",{exact:true}).fill("Tênis azul");
  await page.getByRole("button",{name:"Preços",exact:true}).click();
  await page.getByLabel("Preço (R$) *",{exact:true}).fill("150,00");
  await page.getByRole("button",{name:"Estoque",exact:true}).click();
  await page.getByLabel("Quantidade em estoque").fill("12");
  await page.getByLabel("Código de barras",{exact:true}).fill("7891234567890");
  await page.getByRole("button",{name:"Fotos",exact:true}).click();
  await page.locator('input[type="file"]').setInputFiles({name:"produto.png",mimeType:"image/png",buffer:Buffer.from("iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+a1ioAAAAASUVORK5CYII=","base64")});
  await page.getByRole("button",{name:"Informações",exact:true}).click();
  await expect(page.getByLabel("Nome *",{exact:true})).toHaveValue("Tênis azul");
  await page.getByRole("button",{name:"Salvar produto",exact:true}).click();
  await page.waitForURL("**/admin/products/**");
  const created=await page.evaluate(()=>window.editorSaved);
  expect(created.input.stockQuantity).toBe(12);expect(created.input.priceCents).toBe(15000);
  expect(created.input.barcode).toBe("7891234567890");expect(created.photos).toHaveLength(1);
  await page.goto("http://127.0.0.1:5188/admin/products/11111111-1111-4111-8111-111111111111");
  await page.getByRole("button",{name:"Estoque",exact:true}).click();
  await page.getByLabel("Quantidade em estoque").fill("9");
  await page.getByRole("button",{name:"Salvar produto",exact:true}).click();
  await expect(page.getByRole("status")).toContainText("Produto salvo");
  const edited=await page.evaluate(()=>window.editorSaved);
  expect(edited.expectedStockQuantity).toBe(6);expect(edited.input.stockQuantity).toBe(9);
  await page.goto("http://127.0.0.1:5188");
  await page.getByLabel("Nome *",{exact:true}).fill("Camiseta");
  await page.getByLabel("Este produto tem tamanhos, cores ou outras opções?").check();
  await page.getByRole("button",{name:"Tamanhos, cores e opções",exact:true}).click();
  await page.getByLabel("Valores",{exact:true}).first().fill("P, M");
  await page.getByRole("button",{name:"Preços",exact:true}).click();
  await page.getByLabel("Preço (R$) *",{exact:true}).fill("99,00");
  await page.getByRole("button",{name:"Tamanhos, cores e opções",exact:true}).click();
  await expect(page.getByLabel("Valores",{exact:true}).first()).toHaveValue("P, M");
  await page.getByRole("button",{name:"Gerar combinações",exact:true}).click();
  await page.getByLabel("Quantidade em estoque").nth(1).fill("3");
  await page.getByLabel("Quantidade em estoque").nth(2).fill("5");
  await page.getByRole("button",{name:"Salvar produto",exact:true}).click();
  await page.waitForURL("**/admin/products/**");
  const varied=await page.evaluate(()=>window.editorSaved);
  expect(varied.variants.map(v=>v.stockQuantity)).toEqual([3,5]);
  await page.setViewportSize({width:390,height:844});
  await page.goto("http://127.0.0.1:5188");
  const style=await page.getByRole("button",{name:"Informações",exact:true}).evaluate(el=>({color:getComputedStyle(el.querySelector("span")).color,bg:getComputedStyle(el).backgroundColor}));
  expect(style.color).toBe("rgb(255, 255, 255)");expect(style.bg).toBe("rgb(29, 78, 216)");
  expect(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth)).toBe(true);
  await page.screenshot({path:"/tmp/kataluu-product-mobile.png",fullPage:true});
  expect(errors).toEqual([]);
  process.stderr.write("PASS: criação com foto e estoque, edição, opções, retenção entre abas, contraste e largura mobile.\n");
}catch(error){if(page){process.stderr.write((await page.locator("body").innerText())+"\n");process.stderr.write(JSON.stringify(await page.evaluate(()=>({saved:window.editorSaved,uploads:window.editorUploads})))+"\n");}throw error;}finally{
  await browser?.close();server.kill();await once(server,"exit");
}
