import { createFileRoute, Link } from "@tanstack/react-router";
import { EmptyState } from "../admin/ui/EmptyState.tsx";
import { PageHeader } from "../admin/ui/PageHeader.tsx";
import { Section } from "../admin/ui/Section.tsx";
import { StatusDot } from "../admin/ui/StatusDot.tsx";
import { statusLabel } from "../lib/ui-labels.ts";
import { getMerchantCatalogOverview, getMerchantStorefrontStatus } from "../lib/server/catalog.functions.ts";
export const Route = createFileRoute("/admin/store/")({ loader: async () => { const [catalog, storefront] = await Promise.all([getMerchantCatalogOverview(), getMerchantStorefrontStatus()]); return { catalog, storefront }; }, pendingComponent: () => <EmptyState title="Carregando sua loja" description="Buscando catálogo, domínio e publicação." />, errorComponent: ({ error }) => <EmptyState title="Não foi possível carregar sua loja" description={error instanceof Error ? error.message : "Tente novamente em instantes."} />, component: StorePage });
function statusTone(status:string):"default"|"ok"|"warning"|"danger"{const s=status.toLowerCase();if(["active","verified","published","paid","completed"].includes(s))return"ok";if(["pending","draft","processing"].includes(s))return"warning";if(["inactive","failed","blocked","suspended","cancelled","canceled"].includes(s))return"danger";return"default";}
function StorePage():React.JSX.Element{const{catalog,storefront}=Route.useLoaderData();const domain=storefront.domain;return <><PageHeader title="Minha loja" description="Configure a experiência pública e acompanhe a disponibilidade da sua loja."/><Section title="Experiência da loja" description="Identidade, conteúdo e checkout organizados por área."><div className="k-config-list"><Link className="k-config-row" to="/admin/store/appearance"><span><strong>Aparência</strong><small>Layout, cores e tipografia.</small></span><b aria-hidden="true">→</b></Link><Link className="k-config-row" to="/admin/store/banners"><span><strong>Banners</strong><small>{catalog.banners.length===1?"1 banner cadastrado":`${catalog.banners.length} banners cadastrados`}.</small></span><b aria-hidden="true">→</b></Link><Link className="k-config-row" to="/admin/store/catalog"><span><strong>Catálogo e checkout</strong><small>{catalog.products.total===1?"1 produto":`${catalog.products.total} produtos`} · busca, categorias, WhatsApp e SEO.</small></span><b aria-hidden="true">→</b></Link></div></Section><Section title="Loja pública" description={domain?.hostname??"Domínio ainda não configurado"} action={domain?.previewUrl?<a className="k-button" href={domain.previewUrl} target="_blank" rel="noreferrer">Abrir loja pública ↗</a>:undefined}><dl className="k-detail-list"><div><dt>Loja</dt><dd><StatusDot label={statusLabel(storefront.store.storeStatus)} tone={statusTone(storefront.store.storeStatus)}/></dd></div><div><dt>White Label</dt><dd><StatusDot label={statusLabel(storefront.store.tenantStatus)} tone={statusTone(storefront.store.tenantStatus)}/></dd></div>{domain?<div><dt>Domínio</dt><dd><StatusDot label={statusLabel(domain.status)} tone={statusTone(domain.status)}/></dd></div>:null}</dl>{!domain?.previewUrl?<p className="k-inline-state">A loja pública fica disponível quando o domínio estiver ativo e verificado.</p>:null}</Section></>;}
