import { createFileRoute } from "@tanstack/react-router";
import { handlePaymentWebhook } from "../lib/server/payment-webhook.server.ts";

// @ts-expect-error routeTree.gen.ts is regenerated by TanStack during build for this new file route.
export const Route = createFileRoute("/api/webhooks/$provider/$gatewayAccountId")({
  server: {
    handlers: {
      POST: ({ request }) => {
        const parts = new URL(request.url).pathname.split("/").filter(Boolean);
        const provider = parts.at(-2) ?? "";
        const gatewayAccountId = parts.at(-1) ?? "";
        return handlePaymentWebhook(request, provider, gatewayAccountId);
      },
    },
  },
});
