import { createFileRoute } from "@tanstack/react-router";
import { handleMercadoPagoStoreWebhook } from "../lib/server/payment-webhook.server.ts";
// @ts-expect-error routeTree.gen.ts is regenerated by TanStack during build for this new file route.
export const Route = createFileRoute("/api/webhooks/mercadopago")({
  server: { handlers: { POST: ({ request }) => handleMercadoPagoStoreWebhook(request) } },
});
