import { createFileRoute } from "@tanstack/react-router";
import { handlePaymentWebhook } from "../lib/server/payment-webhook.server.ts";

// @ts-expect-error routeTree.gen.ts is regenerated by TanStack during build for this new file route.
export const Route = createFileRoute("/api/webhooks/$provider/$gatewayAccountId")({
  server: {
    handlers: {
      POST: ({ request, params }) =>
        handlePaymentWebhook(request, params.provider, params.gatewayAccountId),
    },
  },
});
