import { useState } from "react";
import { createFileRoute } from "@tanstack/react-router";
import { MasterEmptyState,MasterPageHeader,MasterPanel } from "../components/master/ui.tsx";
import { masterDate } from "../components/master/format.ts";
import { MasterWhiteLabelCreateForm } from "../features/master/master-white-label-create-form.tsx";
import { listMasterWhiteLabels } from "../lib/server/master-white-label.functions.ts";
import type { MasterWhiteLabelListResult } from "../lib/server/master-white-label.types.ts";

export const Route=createFileRoute("/master/platforms")({loader:()=>listMasterWhiteLabels({data:{page:1,pageSize:20,search:"",status:"all"}}),component:MasterPlatforms});
function MasterPlatforms():React.JSX.Element{
  const initial=Route.useLoaderData();const [data,setData]=useState<MasterWhiteLabelListResult>(initial);const [search,setSearch]=useState("");const [status,setStatus]=useState<"all"|"trial"|"active"|"suspended">("all");const [busy,setBusy]=useState(false);const [message,setMessage]=useState("");
  async function load(page:number):Promise<void>{setBusy(true);setMessage("");try{setData(await listMasterWhiteLabels({data:{search,status,page,pageSize:20}}));}catch(error){setMessage(error instanceof Error?error.message:"Falha ao listar White Labels.");}finally{setBusy(false);}}
  return <div className="master-stack"><MasterPageHeader title="Plataformas" description="Gestão real das White Labels conectadas à Kataluu."/><MasterWhiteLabelCreateForm/><MasterPanel title="White Labels"><form className="k-form" onSubmit={(event)=>{event.preventDefault();void load(1);}}><div className="k-form__grid"><div className="k-field"><label htmlFor="wl-search">Busca</label><input id="wl-search" value={search} onChange={(event)=>{setSearch(event.target.value);}} placeholder="Nome ou slug"/></div><div className="k-field"><label htmlFor="wl-status">Status</label><select id="wl-status" value={status} onChange={(event)=>{setStatus(event.target.value as typeof status);}}><option value="all">Todos</option><option value="trial">Trial</option><option value="active">Active</option><option value="suspended">Suspended</option></select></div></div><div className="k-actions"><button className="k-button" disabled={busy}>Buscar</button></div></form>{message?<div className="k-status">{message}</div>:null}{data.items.length?<><div className="master-table-wrap"><table className="master-table"><thead><tr><th>Plataforma</th><th>Status</th><th>Owner</th><th>Lojas</th><th>Domínios</th><th>Criada em</th></tr></thead><tbody>{data.items.map((tenant)=><tr key={tenant.id}><td><a href={`/master/platforms/${tenant.id}`}><strong>{tenant.name}</strong></a><small>{tenant.slug}</small></td><td>{tenant.status}</td><td>{tenant.ownerEmail??tenant.ownerUserId??"—"}</td><td>{tenant.storeCount}</td><td>{tenant.domainCount}</td><td>{masterDate(tenant.createdAt)}</td></tr>)}</tbody></table></div><div className="k-actions"><button className="k-button" disabled={busy||data.page<=1} onClick={()=>{void load(data.page-1);}}>Anterior</button><span>Página {data.page} de {data.pageCount} · {data.total} registros</span><button className="k-button" disabled={busy||data.page>=data.pageCount} onClick={()=>{void load(data.page+1);}}>Próxima</button></div></>:<MasterEmptyState title="Nenhuma White Label" description="Nenhum registro corresponde aos filtros informados."/>}</MasterPanel></div>;
}
