import { useState } from "react";
import { useRouter } from "@tanstack/react-router";
import type { PlanTemplateView, TenantCommercialPlan, TenantPlanCatalog, TenantPlanEntitlementInput, TenantPlanInput } from "@white-label/billing";
import { saveControlPlan, saveControlPlanEntitlements } from "../../lib/server/commercial-plans.functions.ts";

function formText(form: FormData, key: string, fallback = ""): string { const value = form.get(key); return typeof value === "string" ? value : fallback; }
function centsFromInput(value: string): number { const parsed = Number(value.trim().replace(/\./g, "").replace(",", ".")); if (!Number.isFinite(parsed) || parsed < 0) throw new Error("Preço inválido"); return Math.round(parsed * 100); }
function centsToInput(cents: number): string { return (cents / 100).toFixed(2).replace(".", ","); }
function slugFromTemplate(template: PlanTemplateView): string { return template.code.replaceAll("_", "-"); }
function billingInterval(form: FormData): TenantPlanInput["billingInterval"] { const value = formText(form, "billingInterval"); if (value === "monthly" || value === "quarterly" || value === "yearly") return value; throw new Error("Periodicidade inválida"); }
function planInput(form: FormData, template: PlanTemplateView): TenantPlanInput { const trialEnabled = form.get("trialEnabled") === "on"; return { templateId: template.id, slug: formText(form, "slug", slugFromTemplate(template)), name: formText(form, "name", template.name), description: formText(form, "description").trim() || null, priceCents: centsFromInput(formText(form, "price")), billingInterval: billingInterval(form), active: form.get("active") === "on", trialEnabled, trialDays: trialEnabled ? Number(formText(form, "trialDays", "0")) : 0, displayOrder: Number(formText(form, "displayOrder", String(template.sortOrder))), recommended: form.get("recommended") === "on" }; }
function entitlementPayload(form: FormData, template: PlanTemplateView): TenantPlanEntitlementInput[] { return template.entitlements.map((item) => item.kind === "feature" ? { key: item.key, kind: item.kind, enabled: form.get(`feature:${item.key}`) === "on", limitValue: null } : { key: item.key, kind: item.kind, enabled: null, limitValue: Number(formText(form, `limit:${item.key}`, "0")) }); }

function PlanEntitlements(props: Readonly<{ template: PlanTemplateView; plan: TenantCommercialPlan; busy: boolean; onSave: (values: TenantPlanEntitlementInput[]) => Promise<void> }>): React.JSX.Element {
  const current = new Map(props.plan.entitlements.map((item) => [item.key, item]));
  if (!props.template.entitlements.length) return <div className="control-empty"><strong>Sem recursos configuráveis</strong><p>A Kataluu ainda não autorizou features ou limites para este template.</p></div>;
  return <form className="control-plan-entitlements" onSubmit={(event) => { event.preventDefault(); void props.onSave(entitlementPayload(new FormData(event.currentTarget), props.template)); }}><div className="control-plan-subhead"><div><h4>Recursos e limites</h4><p>Somente itens autorizados pela Kataluu podem ser configurados.</p></div></div>{props.template.entitlements.map((item) => { const saved = current.get(item.key); return item.kind === "feature" ? <label className="control-plan-feature" key={item.key}><input type="checkbox" name={`feature:${item.key}`} defaultChecked={saved?.enabled === true} disabled={item.enabled !== true} /><span><strong>{item.name}</strong><small>{item.key}</small></span><em>{item.enabled === true ? "Permitido" : "Bloqueado pela Kataluu"}</em></label> : <label className="control-plan-limit" key={item.key}><span><strong>{item.name}</strong><small>Teto Kataluu: {item.limitValue ?? 0} {item.unit ?? ""}</small></span><input type="number" min={0} max={item.limitValue ?? 0} name={`limit:${item.key}`} defaultValue={saved?.limitValue ?? 0} /></label>; })}<button className="control-plan-button" disabled={props.busy} type="submit">Salvar recursos</button></form>;
}

function PlanDetailsForm(props: Readonly<{ template: PlanTemplateView; plan?: TenantCommercialPlan; busy: boolean; onSubmit: (event: React.SyntheticEvent<HTMLFormElement>) => void }>): React.JSX.Element {
  return <form className="control-plan-form" onSubmit={props.onSubmit}><fieldset className="control-plan-fieldset"><legend>Oferta</legend><div className="control-plan-form__grid"><label>Nome comercial<input name="name" required defaultValue={props.plan?.name ?? props.template.name} /></label><label>Slug<input name="slug" required defaultValue={props.plan?.slug ?? slugFromTemplate(props.template)} /></label><label className="control-plan-form__wide">Descrição<textarea name="description" defaultValue={props.plan?.description ?? ""} /></label></div></fieldset><fieldset className="control-plan-fieldset"><legend>Cobrança e ciclo</legend><div className="control-plan-form__grid"><label>Preço (R$)<input name="price" inputMode="decimal" required defaultValue={centsToInput(props.plan?.priceCents ?? 0)} /></label><label>Periodicidade<select name="billingInterval" defaultValue={props.plan?.billingInterval ?? "monthly"}><option value="monthly">Mensal</option><option value="quarterly">Trimestral</option><option value="yearly">Anual</option></select></label><label>Ordem<input name="displayOrder" type="number" min={0} defaultValue={props.plan?.displayOrder ?? props.template.sortOrder} /></label><label>Dias de trial<input name="trialDays" type="number" min={0} max={365} defaultValue={props.plan?.trialDays ?? 0} /></label></div></fieldset><fieldset className="control-plan-fieldset control-plan-fieldset--compact"><legend>Disponibilidade</legend><div className="control-plan-options"><label className="control-plan-check"><input name="active" type="checkbox" defaultChecked={props.plan?.active ?? true} />Ativo</label><label className="control-plan-check"><input name="trialEnabled" type="checkbox" defaultChecked={props.plan?.trialEnabled ?? false} />Trial habilitado</label><label className="control-plan-check"><input name="recommended" type="checkbox" defaultChecked={props.plan?.recommended ?? false} />Recomendado</label></div></fieldset><div className="control-plan-actions"><button className="control-plan-button" disabled={props.busy} type="submit">{props.plan ? "Salvar plano" : "Ativar e salvar"}</button></div></form>;
}

function TemplateCard(props: Readonly<{ template: PlanTemplateView; plan?: TenantCommercialPlan }>): React.JSX.Element {
  const router = useRouter(); const [busy, setBusy] = useState(false); const [message, setMessage] = useState("");
  async function savePlan(event: React.SyntheticEvent<HTMLFormElement>): Promise<void> {
    event.preventDefault(); setBusy(true); setMessage("");
    try { await saveControlPlan({ data: planInput(new FormData(event.currentTarget), props.template) }); setMessage("Plano salvo."); await router.invalidate(); }
    catch (error) { setMessage(error instanceof Error ? error.message : "Não foi possível salvar o plano."); }
    finally { setBusy(false); }
  }
  async function saveEntitlements(values: TenantPlanEntitlementInput[]): Promise<void> {
    if (!props.plan) return; setBusy(true); setMessage("");
    try { await saveControlPlanEntitlements({ data: { planId: props.plan.id, values } }); setMessage("Recursos atualizados."); await router.invalidate(); }
    catch (error) { setMessage(error instanceof Error ? error.message : "Não foi possível salvar os recursos."); }
    finally { setBusy(false); }
  }
  return <details className="control-card control-plan-card"><summary className="control-plan-summary"><div><span className="control-kicker">Template Kataluu</span><strong>{props.template.name}</strong><small>{props.template.description ?? "Sem descrição."}</small></div><div className="control-plan-summary__meta"><span>{props.plan ? `R$ ${centsToInput(props.plan.priceCents)} · ${props.plan.billingInterval}` : "Configuração pendente"}</span><span className="control-badge">{props.plan ? (props.plan.active ? "Ativo" : "Inativo") : "Disponível"}</span></div></summary><div className="control-plan-card__body"><PlanDetailsForm template={props.template} plan={props.plan} busy={busy} onSubmit={(event) => { void savePlan(event); }} />{message ? <div className="control-plan-message" role="status">{message}</div> : null}{props.plan ? <PlanEntitlements template={props.template} plan={props.plan} busy={busy} onSave={saveEntitlements} /> : null}</div></details>;
}

export function ControlPlanManager({ catalog }: Readonly<{ catalog: TenantPlanCatalog }>): React.JSX.Element {
  const plans = new Map(catalog.plans.map((plan) => [plan.templateId, plan]));
  return <div className="control-plan-list">{catalog.templates.length ? catalog.templates.map((template) => <TemplateCard key={template.id} template={template} plan={plans.get(template.id)} />) : <div className="control-empty"><strong>Nenhum template disponível</strong><p>A Kataluu ainda não disponibilizou templates de plano ativos para esta White Label.</p></div>}</div>;
}
