import { useState } from "react";
import { useRouter } from "@tanstack/react-router";
import { connectMelhorEnvio, saveMelhorEnvioProfile } from "../../lib/server/melhor-envio.functions.ts";

export function MelhorEnvioCard(props:Readonly<{connected:boolean;enabled:boolean;postalCode:string|null;shipperName:string|null}>):React.JSX.Element{
 const [busy,setBusy]=useState(false),[message,setMessage]=useState("");const [profile,setProfile]=useState({postalCode:props.postalCode??"",shipperName:props.shipperName??"",shipperEmail:"",shipperPhone:"",document:"",companyDocument:"",stateRegister:"",address:"",number:"",complement:"",district:"",city:"",stateAbbr:"",enabled:props.enabled});const router=useRouter();
 async function save():Promise<void>{setBusy(true);setMessage("");try{await saveMelhorEnvioProfile({data:{...profile,document:profile.document||null,companyDocument:profile.companyDocument||null,stateRegister:profile.stateRegister||null,complement:profile.complement||null}});setMessage("Perfil de expedição salvo.");await router.invalidate();}catch(e){setMessage(e instanceof Error?e.message:"Não foi possível salvar.");}finally{setBusy(false);}}
 async function connect():Promise<void>{setBusy(true);setMessage("");try{const r=await connectMelhorEnvio();window.location.assign(r.authorizationUrl);}catch{setMessage("Não foi possível iniciar a conexão com o Melhor Envio.");setBusy(false);}}
 return <div className="k-card"><div className="k-card__header"><div><h3>Melhor Envio</h3><p>Cotações, etiquetas e rastreamento da entrega.</p></div><span className={props.connected?"k-status k-success":"k-status"}>{props.connected?"Conectado":"Não conectado"}</span></div>
 <p className="k-muted">{props.enabled&&props.postalCode?`Origem de frete: ${props.postalCode}`:"Complete o perfil de expedição para liberar cotações no checkout."}</p>
 <div className="k-form-grid">{([["shipperName","Nome do remetente"],["shipperEmail","E-mail"],["shipperPhone","Telefone"],["postalCode","CEP"],["address","Endereço"],["number","Número"],["district","Bairro"],["city","Cidade"],["stateAbbr","UF"],["document","CPF"],["companyDocument","CNPJ"],["stateRegister","Inscrição estadual"],["complement","Complemento"]] as const).map(([key,label])=><label className="k-field" key={key}><span>{label}</span><input value={profile[key]} onChange={e=>setProfile({...profile,[key]:e.target.value})}/></label>)}<label className="k-field"><span>Frete ativo</span><input type="checkbox" checked={profile.enabled} onChange={e=>setProfile({...profile,enabled:e.target.checked})}/></label></div>
 {message?<p className="k-status k-danger">{message}</p>:null}<div className="k-actions"><button className="k-button k-button--primary" disabled={busy} type="button" onClick={()=>{void save();}}>Salvar expedição</button><button className="k-button k-button--primary" disabled={busy} type="button" onClick={()=>{void connect();}}>{busy?"Abrindo…":props.connected?"Reconectar Melhor Envio":"Conectar Melhor Envio"}</button><button className="k-button" type="button" onClick={()=>{void router.invalidate();}}>Atualizar status</button></div></div>;
}
