import { useState } from "react";
import type { SyntheticEvent } from "react";
import { useRouter } from "@tanstack/react-router";
import type { ProductVariant, VariantMutationInput } from "@white-label/catalog";
import { createMerchantVariant, updateMerchantVariant } from "../../lib/server/catalog-admin.functions.ts";
import { centsToInput, moneyToCents } from "./format.ts";
interface VariantDraft { name: string; sku: string; price: string; compareAt: string; cost: string; stock: string; position: string; attributes: string; active: boolean; }
function attributesToText(attributes: Record<string, string>): string { return Object.entries(attributes).map(([key, value]) => `${key}=${value}`).join("\n"); }
function parseAttributes(value: string): Record<string, string> { const attributes: Record<string, string> = {}; for (const rawLine of value.split("\n")) { const line = rawLine.trim(); if (!line) continue; const separator = line.indexOf("="); if (separator <= 0) throw new Error("Preencha o nome e o valor de cada opção."); const key = line.slice(0, separator).trim(); const itemValue = line.slice(separator + 1).trim(); if (!key || key.length > 80 || !itemValue || itemValue.length > 120) throw new Error("Opção de variação inválida."); if (Object.prototype.hasOwnProperty.call(attributes, key)) throw new Error(`Opção repetida: ${key}`); attributes[key] = itemValue; } return attributes; }
function initialDraft(variant?: ProductVariant): VariantDraft { return { name: variant?.name ?? "", sku: variant?.sku ?? "", price: centsToInput(variant?.priceCents ?? 0), compareAt: centsToInput(variant?.compareAtPriceCents ?? null), cost: centsToInput(variant?.costCents ?? null), stock: String(variant?.stockQuantity ?? 0), position: String(variant?.position ?? 0), attributes: attributesToText(variant?.attributes ?? {}), active: variant?.active ?? true }; }
function optionalCents(value: string): number | null { return value.trim() ? moneyToCents(value) : null; }
function nonNegativeInteger(value: string, label: string): number { const parsed = Number.parseInt(value || "0", 10); if (!Number.isSafeInteger(parsed) || parsed < 0) throw new Error(`${label} inválido`); return parsed; }
function toInput(productId: string, draft: VariantDraft): VariantMutationInput { return { productId, name: draft.name.trim(), sku: draft.sku.trim() || null, attributes: parseAttributes(draft.attributes), priceCents: moneyToCents(draft.price), compareAtPriceCents: optionalCents(draft.compareAt), costCents: optionalCents(draft.cost), active: draft.active, stockQuantity: nonNegativeInteger(draft.stock, "Estoque"), position: nonNegativeInteger(draft.position, "Posição") }; }
type OptionRow = { name: string; value: string };
function optionRows(text: string): OptionRow[] { const rows: OptionRow[] = []; for (const line of text.split("\n")) { if (!line) continue; const separator = line.indexOf("="); rows.push(separator > 0 ? { name: line.slice(0, separator), value: line.slice(separator + 1) } : { name: line, value: "" }); } if (rows.length === 0) rows.push({ name: "", value: "" }); return rows; }
function rowsToText(rows: OptionRow[]): string { return rows.filter((row) => row.name.trim() || row.value.trim()).map((row) => `${row.name.trim()}=${row.value.trim()}`).join("\n"); }
function VariationOptions({ value, onChange }: Readonly<{ value: string; onChange: (value: string) => void }>): React.JSX.Element { const rows = optionRows(value); function update(index: number, key: keyof OptionRow, next: string): void { const copy = rows.map((row) => ({ ...row })); const row = copy[index]; if (!row) return; row[key] = next; onChange(rowsToText(copy)); } function add(): void { const base = rowsToText(rows); onChange(`${base}${base ? "\n" : ""}Nova opção=`); } function remove(index: number): void { onChange(rowsToText(rows.filter((_, i) => i !== index))); } return <div className="k-field k-field--full"><span>Opções desta variação</span><p className="k-muted">Ex.: Tamanho → M, Cor → Azul. Você não precisa escrever códigos.</p><div className="k-record-list">{rows.map((row, index) => <div className="k-form__grid" key={`${String(index)}-${row.name}`}><label className="k-field"><span>Tipo</span><input value={row.name} placeholder="Ex.: Tamanho" onChange={(event) => { update(index, "name", event.target.value); }} /></label><label className="k-field"><span>Valor</span><input value={row.value} placeholder="Ex.: M" onChange={(event) => { update(index, "value", event.target.value); }} /></label>{rows.length > 1 ? <button className="k-button" type="button" onClick={() => { remove(index); }}>Remover opção</button> : null}</div>)}</div><button className="k-button" type="button" onClick={add}>+ Adicionar opção</button></div>; }
function VariantFields(props: Readonly<{ draft: VariantDraft; setField: <K extends keyof VariantDraft>(key: K, value: VariantDraft[K]) => void }>): React.JSX.Element { const { draft, setField } = props; return <div className="k-form__grid"><label className="k-field k-field--full"><span>Nome da variação</span><input value={draft.name} onChange={(event) => { setField("name", event.target.value); }} placeholder="Ex.: Camiseta azul M" required /><span className="k-muted">Use um nome que você reconheça rapidamente nos pedidos.</span></label><VariationOptions value={draft.attributes} onChange={(value) => { setField("attributes", value); }} /><label className="k-field"><span>Preço</span><input inputMode="decimal" value={draft.price} onChange={(event) => { setField("price", event.target.value); }} required /></label><label className="k-field"><span>Preço promocional/de</span><input inputMode="decimal" value={draft.compareAt} onChange={(event) => { setField("compareAt", event.target.value); }} /></label><label className="k-field"><span>SKU <small>(opcional)</small></span><input value={draft.sku} onChange={(event) => { setField("sku", event.target.value); }} /></label><details className="k-field k-field--full"><summary>Mais opções</summary><div className="k-form__grid"><label className="k-field"><span>Custo interno</span><input inputMode="decimal" value={draft.cost} onChange={(event) => { setField("cost", event.target.value); }} /></label><label className="k-field"><span>Ordem</span><input type="number" min="0" value={draft.position} onChange={(event) => { setField("position", event.target.value); }} /></label><label className="k-field"><span>Estoque atual</span><input type="number" min="0" value={draft.stock} disabled readOnly /><span className="k-muted">Ajuste pela área Estoque.</span></label></div></details></div>; }
function VariantSummary({ variant }: Readonly<{ variant?: ProductVariant }>): React.JSX.Element { const label = variant ? variant.name : "+ Criar uma variação"; const options = variant ? Object.values(variant.attributes).join(" · ") : "Tamanho, cor, material ou qualquer outra opção"; return <summary><span><strong>{label}</strong><small>{options || "Sem opções"}</small></span>{variant ? <span className={variant.active ? "k-status-pill k-status-pill--active" : "k-status-pill"}>{variant.active ? "Ativa" : "Inativa"}</span> : null}</summary>; }
function VariantForm(props: Readonly<{ productId: string; variant?: ProductVariant }>): React.JSX.Element { const router = useRouter(); const [draft, setDraft] = useState(() => initialDraft(props.variant)); const [saving, setSaving] = useState(false); const [status, setStatus] = useState(""); function setField<K extends keyof VariantDraft>(key: K, value: VariantDraft[K]): void { setDraft((current) => ({ ...current, [key]: value })); } async function submit(event: SyntheticEvent<HTMLFormElement>): Promise<void> { event.preventDefault(); setSaving(true); setStatus(""); try { const input = toInput(props.productId, draft); if (props.variant) { const updated = await updateMerchantVariant({ data: { id: props.variant.id, input } }); if (!updated) throw new Error("Variação não encontrada neste produto"); } else await createMerchantVariant({ data: input }); setStatus("Variação salva."); await router.invalidate(); if (!props.variant) setDraft(initialDraft()); } catch (error) { setStatus(error instanceof Error ? error.message : "Não foi possível salvar a variação."); } finally { setSaving(false); } } return <details className="k-record-editor" open={!props.variant}><VariantSummary variant={props.variant} /><form className="k-record-editor__form" onSubmit={(event) => { void submit(event); }}><VariantFields draft={draft} setField={setField} /><div className="k-record-editor__footer"><label className="k-check"><input type="checkbox" checked={draft.active} onChange={(event) => { setField("active", event.target.checked); }} />Disponível no catálogo</label>{status ? <span className="k-status" role="status">{status}</span> : null}<button className="k-button k-button--primary" type="submit" disabled={saving}>{saving ? "Salvando…" : props.variant ? "Salvar variação" : "Adicionar variação"}</button></div></form></details>; }
export function VariantEditor(props: Readonly<{ productId: string; variants: ProductVariant[] }>): React.JSX.Element { const count = props.variants.length; const countLabel = `${String(count)} ${count === 1 ? "cadastrada" : "cadastradas"}`; return <section className="k-workspace-section"><header className="k-section-head"><div><span className="k-section-kicker">VARIAÇÕES</span><h2>Este produto tem opções?</h2><p>Crie tamanhos, cores ou qualquer combinação. Cada variação pode ter preço e SKU próprios.</p></div><span className="k-section-count">{countLabel}</span></header><div className="k-record-list"><VariantForm productId={props.productId} />{props.variants.map((variant) => <VariantForm key={variant.id} productId={props.productId} variant={variant} />)}</div></section>; }
