import { useMemo, useState } from "react";
import { useRouter } from "@tanstack/react-router";
import type { Coupon, CouponMutationInput, CouponDisplayStatus } from "@white-label/marketing";
import { getCouponDisplayStatus } from "@white-label/marketing";
import { centsToInput, moneyToCents } from "./format.ts";
import { createMerchantCoupon, updateMerchantCoupon } from "../../lib/server/operations-marketing.functions.ts";

function field(form: FormData,key:string):string{const value=form.get(key);return typeof value==="string"?value:"";}
function toIso(value:string):string|null{const text=value.trim();return text?new Date(text).toISOString():null;}
function readCoupon(form:FormData):CouponMutationInput{const type=field(form,"discountType")==="fixed"?"fixed":"percentage",rawValue=field(form,"discountValue"),minimum=field(form,"minimumOrder").trim(),limit=field(form,"usageLimit").trim();return{code:field(form,"code"),name:field(form,"name"),active:form.get("active")==="on",discountType:type,discountValue:type==="percentage"?Number(rawValue):moneyToCents(rawValue),minimumOrderCents:minimum?moneyToCents(minimum):null,startsAt:toIso(field(form,"startsAt")),endsAt:toIso(field(form,"endsAt")),usageLimit:limit?Number(limit):null};}
function CouponFields({coupon}:Readonly<{coupon?:Coupon}>):React.JSX.Element{const percentage=coupon?.discountType!=="fixed";return <div className="k-form__grid"><div className="k-field"><label>Código</label><input name="code" defaultValue={coupon?.code??""} required /></div><div className="k-field"><label>Nome</label><input name="name" defaultValue={coupon?.name??""} required /></div><div className="k-field"><label>Tipo</label><select name="discountType" defaultValue={coupon?.discountType??"percentage"}><option value="percentage">Percentual</option><option value="fixed">Valor fixo</option></select></div><div className="k-field"><label>Valor</label><input name="discountValue" defaultValue={coupon?(percentage?String(coupon.discountValue):centsToInput(coupon.discountValue)):""} required /></div><div className="k-field"><label>Pedido mínimo (R$)</label><input name="minimumOrder" defaultValue={centsToInput(coupon?.minimumOrderCents??null)} /></div><div className="k-field"><label>Limite de usos</label><input name="usageLimit" type="number" min={1} defaultValue={coupon?.usageLimit??""} /></div><div className="k-field"><label>Início</label><input name="startsAt" type="datetime-local" defaultValue={coupon?.startsAt?.slice(0,16)??""} /></div><div className="k-field"><label>Fim</label><input name="endsAt" type="datetime-local" defaultValue={coupon?.endsAt?.slice(0,16)??""} /></div><label className="k-check"><input name="active" type="checkbox" defaultChecked={coupon?.active??true} />Ativo</label></div>;}
function statusLabel(status:CouponDisplayStatus):string{if(status==="active")return"Ativo";if(status==="scheduled")return"Agendado";if(status==="expired")return"Expirado";if(status==="exhausted")return"Esgotado";return"Inativo";}
function matches(coupon:Coupon,rawSearch:string):boolean{const search=rawSearch.trim().toLocaleLowerCase("pt-BR");return !search||coupon.code.toLocaleLowerCase("pt-BR").includes(search)||coupon.name.toLocaleLowerCase("pt-BR").includes(search);}
type SaveCoupon=(event:React.SyntheticEvent<HTMLFormElement>,id?:string)=>Promise<void>;
function CouponEditor(props:Readonly<{coupon:Coupon;busy:boolean;save:SaveCoupon}>):React.JSX.Element{const status=getCouponDisplayStatus(props.coupon);return <details className="k-record-editor"><summary><span className="k-record-editor__identity"><strong>{props.coupon.code}</strong><small>{props.coupon.name} · {props.coupon.usageCount}{props.coupon.usageLimit?`/${String(props.coupon.usageLimit)}`:""} usos</small></span><span className={`k-status-pill k-status-pill--${status}`}>{statusLabel(status)}</span></summary><form className="k-record-editor__form" onSubmit={(event)=>{void props.save(event,props.coupon.id);}}><CouponFields coupon={props.coupon}/><div className="k-record-editor__footer"><button className="k-button" disabled={props.busy} type="submit">Salvar cupom</button></div></form></details>;}
function useCouponActions():Readonly<{busy:boolean;message:string;error:string;save:SaveCoupon}>{const router=useRouter(),[message,setMessage]=useState(""),[error,setError]=useState(""),[busy,setBusy]=useState(false);async function save(event:React.SyntheticEvent<HTMLFormElement>,id?:string):Promise<void>{event.preventDefault();const form=event.currentTarget;setBusy(true);setMessage("");setError("");try{const input=readCoupon(new FormData(form));if(id)await updateMerchantCoupon({data:{id,input}});else await createMerchantCoupon({data:input});await router.invalidate();if(!id)form.reset();setMessage(id?"Cupom atualizado.":"Cupom criado e lista atualizada.");}catch(cause){setError(cause instanceof Error?cause.message:"Não foi possível salvar o cupom.");}finally{setBusy(false);}}return{busy,message,error,save};}
export function CouponManager({coupons}:Readonly<{coupons:Coupon[]}>):React.JSX.Element{const{busy,message,error,save}=useCouponActions(),[search,setSearch]=useState("");const visible=useMemo(()=>coupons.filter((coupon)=>matches(coupon,search)),[coupons,search]);return <section className="k-workspace-section"><header className="k-section-head"><div><span className="k-section-kicker">Promoções</span><h2>Cupons</h2><p>Regras promocionais da loja com vigência, limites e desconto validados no servidor.</p></div><span className="k-section-count">{coupons.length} cupom(ns)</span></header><details className="k-composer"><summary><span><strong>Novo cupom</strong><small>Defina código, desconto, vigência e limites.</small></span><span className="k-composer__action">Criar</span></summary><form className="k-composer__body" onSubmit={(event)=>{void save(event);}}><CouponFields/><div className="k-actions"><button className="k-button k-button--primary" disabled={busy} type="submit">{busy?"Salvando…":"Criar cupom"}</button></div></form></details><div className="k-toolbar"><div className="k-toolbar__search"><label className="k-visually-hidden" htmlFor="coupon-search">Pesquisar cupons</label><input id="coupon-search" value={search} onChange={(event)=>{setSearch(event.target.value);}} placeholder="Código ou nome" /></div>{search?<button className="k-button k-button--ghost" type="button" disabled={busy} onClick={()=>{setSearch("");}}>Limpar</button>:null}</div>{error?<div className="k-inline-state k-inline-state--error"><strong>Operação não concluída</strong><span>{error}</span></div>:null}{message?<div className="k-inline-state"><strong>Concluído</strong><span>{message}</span></div>:null}{visible.length===0?<div className="k-inline-state"><strong>Nenhum cupom encontrado</strong><span>Crie um cupom ou ajuste a busca.</span></div>:<div className="k-record-list">{visible.map((coupon)=><CouponEditor key={coupon.id} coupon={coupon} busy={busy} save={save}/>)}</div>}</section>;}
