/* Retail storefront across catalog, categories, product detail and cart. */
export const storefrontMarketTheme = `
@font-face { font-family:"DM Sans";src:url("/fonts/dm-sans-variable.ttf") format("truetype");font-weight:100 1000;font-style:normal;font-display:swap; }
.sf { --sf-ink:#1b1830;--sf-muted:#625e70;--sf-line:#e7e3ee;--sf-soft:#f6f4fa;--sf-surface:#fff; background:#fff;color:var(--sf-ink);font-family:"DM Sans",system-ui,sans-serif; }
.sf__header { position:sticky;top:0;z-index:30;background:#fff;border-bottom:0;box-shadow:0 3px 18px rgba(29,17,55,.09);backdrop-filter:none; }
.sf__header-inner { width:min(1440px,calc(100% - 64px));min-height:86px;gap:28px; }
.sf__logo { max-width:240px;min-width:130px;font-size:clamp(20px,2vw,28px);font-weight:900;letter-spacing:-.065em;color:#47218c!important; }
.sf__header-search-area { position:relative;flex:1;max-width:660px;min-width:0;margin-left:auto; }.sf__header-search { display:flex;align-items:center;height:48px;border:1px solid #ded8e9;border-radius:8px;background:#f8f7fb; }
.sf__header-search:focus-within { border-color:#6b40ad;box-shadow:0 0 0 3px #ede5fa; }
.sf__header-search input { width:100%;height:100%;min-width:0;padding:0 15px;border:0;outline:0;background:transparent;color:var(--sf-ink);font-size:14px; }
.sf__header-search input::placeholder { color:#847e90; }.sf__header-search>span:last-child { padding:0 16px;color:#502593;font-size:29px;line-height:1; }
.sf__header-help { white-space:nowrap;color:#423453!important;text-decoration:none;font-size:13px;font-weight:700; }
.sf__cart-button { gap:8px;min-height:47px;padding:9px 14px;border:0;border-radius:8px;background:#51289a;color:#fff;font-size:13px;font-weight:800;white-space:nowrap; }
.sf__cart-button:hover,.sf__primary:hover { background:#3e197f; }.sf__cart-button>span:first-child { font-size:22px;line-height:1; }
.sf__cart-button strong { color:#51289a; }
.sf__nav { display:block;margin:0;background:#51289a; }.sf__nav-inner { width:min(1440px,calc(100% - 64px));min-height:41px;margin:auto;display:flex;align-items:center;gap:32px; }
.sf__nav a { color:#fff!important;text-decoration:none;font-size:12px;font-weight:750;white-space:nowrap; }.sf__nav a:hover { text-decoration:underline;text-underline-offset:5px; }
.sf__main,.sf__footer,.sf__product-layout { width:min(1440px,calc(100% - 64px)); }.sf__main { padding:0 0 78px; }
.sf__service-strip { display:flex;justify-content:space-between;gap:15px;padding:15px 2px;color:#5c5267;font-size:11px;font-weight:740;letter-spacing:.015em; }
.sf__banner { margin:0 0 22px;border:0;border-radius:10px; }.sf__banner img { max-height:410px;aspect-ratio:3.2/1; }
.sf__hero { display:grid;grid-template-columns:1.02fr .98fr;min-height:340px;overflow:hidden;margin:0 0 22px;border-radius:12px;background:#eee8f9; }
.sf__hero>div:first-child { display:grid;align-content:center;justify-items:start;padding:clamp(30px,5vw,72px); }.sf__hero .sf__eyebrow { color:#6d3caa;font-size:11px;font-weight:850; }
.sf__hero h1 { max-width:520px;margin:10px 0;font-size:clamp(36px,4vw,60px);font-weight:900;line-height:1.02;letter-spacing:-.055em;color:#271145; }
.sf__hero p { max-width:400px;margin:2px 0 23px;color:#5a4871;font-size:15px; }
.sf__hero a { display:inline-flex;gap:20px;align-items:center;min-height:44px;padding:10px 17px;border-radius:7px;background:#51289a;color:#fff;text-decoration:none;font-size:13px;font-weight:800; }
.sf__hero-art { position:relative;display:grid;place-items:center;overflow:hidden;background:radial-gradient(circle at 26% 70%,#b790ed 0 16%,transparent 17%),radial-gradient(circle at 80% 25%,#d9bafd 0 19%,transparent 20%),linear-gradient(135deg,#6739ab,#34205d); }
.sf__hero-art::before { content:"";position:absolute;width:300px;height:300px;border:38px solid rgba(255,255,255,.14);border-radius:50%;transform:translate(55%,-35%); }
.sf__hero-art span { position:relative;z-index:1;color:#fff;font-size:clamp(26px,3vw,47px);font-weight:900;letter-spacing:-.05em;line-height:1.05;transform:rotate(-6deg); }.sf__hero-art i { position:absolute;bottom:16px;right:25px;color:#ffd86e;font-size:90px;font-style:normal; }
.sf__intro { max-width:none;padding:24px 0 20px; }.sf__intro h1 { margin:4px 0 0;font-size:clamp(25px,3vw,34px);line-height:1.17;font-weight:850;letter-spacing:-.045em; }.sf__intro p { margin:8px 0 0;font-size:13px; }
.sf__eyebrow { color:#7643ad;font-size:10px;font-weight:850;letter-spacing:.11em; }.sf__section-head h2 { font-size:clamp(22px,2.4vw,30px);font-weight:850;letter-spacing:-.045em; }.sf__section-head>a { color:#51289a;font-size:12px;font-weight:800;text-decoration:none; }
.sf__categories { padding:18px 0 38px; }.sf__category-list { display:flex;gap:12px;padding:3px 0 8px;border:0;scrollbar-width:thin; }
.sf__category-list a { display:grid;justify-items:center;align-content:start;gap:9px;flex:0 0 125px;min-height:134px;margin:0;padding:12px 7px;border:1px solid var(--sf-line);border-radius:10px;background:#fff;color:#3b3446;text-align:center;white-space:normal;font-size:12px;font-weight:770;line-height:1.25; }
.sf__category-list a span { display:grid;place-items:center;width:70px;height:70px;border-radius:50%;background:#f1ebfa;color:#6130a0;font-size:27px;font-weight:900; }
.sf__category-list a:hover,.sf__category-list a.is-active { border-color:#9f79d2;color:#51289a;box-shadow:0 6px 20px rgba(61,35,99,.09); }.sf__category-list a.is-active span { background:#e1d1f5; }
.sf__products { padding-top:12px;scroll-margin-top:145px; }.sf__toolbar { justify-content:space-between;padding:12px 16px;margin-bottom:16px;border:1px solid var(--sf-line);border-radius:7px;background:#faf9fc;color:var(--sf-muted);font-size:12px; }.sf__toolbar label { display:flex;align-items:center;gap:10px;font-weight:740; }.sf__sort { min-height:37px;min-width:150px;border-color:#ded8e9;border-radius:6px;font-size:12px; }
.sf__grid,.sf__grid.sf__grid--columns-4 { gap:15px; }.sf__product-card { overflow:hidden;border:1px solid var(--sf-line);border-radius:8px;background:#fff;transition:box-shadow .15s,transform .15s; }.sf__product-card:hover { box-shadow:0 10px 30px rgba(44,25,76,.11);transform:translateY(-2px); }
.sf__image,.sf--classic .sf__image { aspect-ratio:1/1;background:#f7f6f9; }.sf__product-link:hover .sf__image img { transform:scale(1.045); }.sf__card-body,.sf__product-card--compact .sf__card-body { display:grid;align-content:start;min-height:150px;padding:13px 14px 15px; }
.sf__fallback-visual { width:100%;height:100%;display:grid;align-content:center;justify-items:center;gap:14px;padding:20px;background:radial-gradient(circle at 80% 22%,#ded4ef 0 14%,transparent 15%),linear-gradient(145deg,#f7f2fd,#e9e0f3);text-align:center; }.sf__fallback-visual span { display:grid;place-items:center;width:88px;height:88px;border:1px solid #d5c3e9;border-radius:50%;color:#764ba9;font-size:54px;line-height:1; }.sf__fallback-visual small { max-width:170px;color:#665373;font-size:11px;font-weight:800;line-height:1.35; }
.sf__product-name { margin:6px 0 10px;font-size:14px;font-weight:750;line-height:1.35;letter-spacing:-.012em; }.sf__meta { color:#82798a;font-size:11px; }.sf__price { color:#281a41;font-size:17px;font-weight:880; }.sf__old-price { color:#8b8492;font-size:12px; }.sf__card-foot { margin-top:12px;padding-top:9px;border-top:1px solid #f0edf4;font-size:11px; }.sf__placeholder { color:#897f95; }
.sf__pagination button { border-radius:7px; }.sf__footer { flex-wrap:wrap;padding:36px 0 55px;border-top:2px solid #51289a; }.sf__footer strong { color:#51289a;font-size:18px;font-weight:900; }.sf__footer a { color:#51289a; }
.sf__breadcrumbs { display:flex;align-items:center;gap:9px;min-height:47px;color:#81788c;font-size:12px; }.sf__breadcrumbs a { color:#583197;text-decoration:none; }.sf__breadcrumbs>a:hover { text-decoration:underline; }.sf__breadcrumbs>span:last-child { overflow:hidden;text-overflow:ellipsis;white-space:nowrap; }.sf__product-layout { padding:25px 0 55px; }.sf__product-title { font-weight:850; }.sf__primary { border-color:#51289a;border-radius:7px;background:#51289a; }.sf__modal { border-radius:12px; }.sf__detail-image { border-radius:8px; }
@media(max-width:950px) { .sf__header-inner,.sf__nav-inner,.sf__main,.sf__footer,.sf__product-layout { width:calc(100% - 36px); }.sf__header-help { display:none; }.sf__grid,.sf__grid.sf__grid--columns-4 { grid-template-columns:repeat(3,minmax(0,1fr)); }.sf__hero { min-height:300px; } }
@media(max-width:700px) { .sf__header-inner { flex-wrap:wrap;min-height:108px;gap:8px 12px;padding:10px 0; }.sf__logo { min-width:0;max-width:calc(100% - 80px);margin-right:auto;font-size:22px; }.sf__cart-button { min-width:46px;min-height:41px;padding:7px 9px; }.sf__cart-button span:nth-child(2) { display:none; }.sf__header-search-area { flex:0 0 100%;order:3;max-width:none; }.sf__header-search { height:42px; }.sf__nav { display:block;overflow:auto;scrollbar-width:none; }.sf__nav-inner { min-width:max-content;min-height:38px;gap:19px; }.sf__service-strip { justify-content:center;gap:8px;padding:9px 0;font-size:10px; }.sf__service-strip span:not(:first-child) { display:none; }.sf__hero { grid-template-columns:1fr;min-height:0; }.sf__hero>div:first-child { padding:30px 24px; }.sf__hero h1 { font-size:35px; }.sf__hero-art { min-height:130px; }.sf__hero-art span { font-size:22px; }.sf__hero-art i { font-size:55px; }.sf__banner img { aspect-ratio:16/7; }.sf__intro { padding:16px 0 12px; }.sf__categories { padding:12px 0 25px; }.sf__category-list { gap:9px; }.sf__category-list a { flex-basis:104px;min-height:119px;font-size:11px; }.sf__category-list a span { width:57px;height:57px;font-size:22px; }.sf__grid,.sf__grid.sf__grid--columns-2,.sf__grid.sf__grid--columns-3,.sf__grid.sf__grid--columns-4 { grid-template-columns:repeat(2,minmax(0,1fr));gap:9px; }.sf__card-body { padding:10px 10px 12px; }.sf__product-name { font-size:12px; }.sf__price { font-size:14px; }.sf__toolbar { gap:8px;align-items:center;flex-direction:row;padding:9px; }.sf__toolbar label { font-size:0; }.sf__sort { width:auto;min-width:125px;min-height:37px;font-size:11px; }.sf__footer { gap:12px; } }
@media(max-width:380px) { .sf__nav-inner { gap:14px; }.sf__nav a { font-size:11px; }.sf__toolbar>span { font-size:10px; } }
`;
