-- Melhor Envio OAuth, freight quotes and order shipment lifecycle.
alter table public.products add column shipping_weight_kg numeric(10,3),add column shipping_width_cm numeric(10,2),add column shipping_height_cm numeric(10,2),add column shipping_length_cm numeric(10,2);
alter table public.products add constraint products_shipping_dims_ck check ((shipping_weight_kg is null and shipping_width_cm is null and shipping_height_cm is null and shipping_length_cm is null) or (shipping_weight_kg>0 and shipping_width_cm>0 and shipping_height_cm>0 and shipping_length_cm>0));
create table private.melhor_envio_accounts(store_id uuid primary key,tenant_id uuid not null,access_token_ciphertext text not null,refresh_token_ciphertext text not null,access_token_expires_at timestamptz not null,connected_at timestamptz not null default now(),updated_at timestamptz not null default now(),foreign key(tenant_id,store_id) references public.stores(tenant_id,id) on delete cascade);
create table private.melhor_envio_oauth_states(state_hash text primary key,tenant_id uuid not null,store_id uuid not null,actor_user_id uuid not null,return_url text not null,expires_at timestamptz not null,consumed_at timestamptz,created_at timestamptz not null default now(),foreign key(tenant_id,store_id) references public.stores(tenant_id,id) on delete cascade);
create table public.store_shipping_profiles(tenant_id uuid not null,store_id uuid not null,postal_code text not null,shipper_name text not null,shipper_email text not null,shipper_phone text not null,document text,company_document text,state_register text,address text not null,number text not null,complement text,district text not null,city text not null,state_abbr text not null,enabled boolean not null default false,updated_at timestamptz not null default now(),primary key(tenant_id,store_id),foreign key(tenant_id,store_id) references public.stores(tenant_id,id) on delete cascade,check(postal_code~'^[0-9]{8}$'));
create table public.order_shipments(id uuid primary key default gen_random_uuid(),tenant_id uuid not null,store_id uuid not null,order_id uuid not null,provider text not null default 'melhor_envio',service_id integer not null,service_name text not null,company_name text,quoted_price_cents bigint not null check(quoted_price_cents>=0),quoted_delivery_days integer,recipient jsonb not null,quote_snapshot jsonb not null,provider_shipment_id text,tracking_code text,status text not null default 'quoted',label_url text,created_at timestamptz not null default now(),updated_at timestamptz not null default now(),foreign key(tenant_id,store_id,order_id) references public.orders(tenant_id,store_id,id) on delete cascade,unique(tenant_id,store_id,order_id),check(status in('quoted','cart','paid','generated','posted','delivered','cancelled','error')));
alter table public.store_shipping_profiles enable row level security;alter table public.order_shipments enable row level security;alter table private.melhor_envio_accounts enable row level security;alter table private.melhor_envio_oauth_states enable row level security;
revoke all on public.store_shipping_profiles,public.order_shipments from public,anon,authenticated;revoke all on private.melhor_envio_accounts,private.melhor_envio_oauth_states from public,anon,authenticated;
create index order_shipments_scope_idx on public.order_shipments(tenant_id,store_id,status,created_at desc);
